os.(*File).close STEXT dupok nosplit size=26 args=0x18 locals=0x0
	0x0000 00000 (<autogenerated>:1)	TEXT	os.(*File).close(SB), DUPOK|NOSPLIT|ABIInternal, $0-24
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$0, gclocals·e6397a44f8e1b6e77d0f200b4fba5269(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$1, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0000 00000 (<autogenerated>:1)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x0000 00000 (<autogenerated>:1)	PCDATA	$0, $1
	0x0000 00000 (<autogenerated>:1)	PCDATA	$1, $1
	0x0000 00000 (<autogenerated>:1)	MOVQ	""..this+8(SP), AX
	0x0005 00005 (<autogenerated>:1)	MOVQ	(AX), AX
	0x0008 00008 (<autogenerated>:1)	PCDATA	$0, $0
	0x0008 00008 (<autogenerated>:1)	PCDATA	$1, $0
	0x0008 00008 (<autogenerated>:1)	MOVQ	AX, ""..this+8(SP)
	0x000d 00013 (<autogenerated>:1)	XORPS	X0, X0
	0x0010 00016 (<autogenerated>:1)	MOVUPS	X0, "".~r0+16(SP)
	0x0015 00021 (<autogenerated>:1)	JMP	os.(*file).close(SB)
	0x0000 48 8b 44 24 08 48 8b 00 48 89 44 24 08 0f 57 c0  H.D$.H..H.D$..W.
	0x0010 0f 11 44 24 10 e9 00 00 00 00                    ..D$......
	rel 22+4 t=8 os.(*file).close+0
"".StringToBytes STEXT nosplit size=88 args=0x28 locals=0x20
	0x0000 00000 (main.go:32)	TEXT	"".StringToBytes(SB), NOSPLIT|ABIInternal, $32-40
	0x0000 00000 (main.go:32)	SUBQ	$32, SP
	0x0004 00004 (main.go:32)	MOVQ	BP, 24(SP)
	0x0009 00009 (main.go:32)	LEAQ	24(SP), BP
	0x000e 00014 (main.go:32)	FUNCDATA	$0, gclocals·9fad110d66c97cf0b58d28cccea80b12(SB)
	0x000e 00014 (main.go:32)	FUNCDATA	$1, gclocals·7d2d5fca80364273fb07d5820a76fef4(SB)
	0x000e 00014 (main.go:32)	FUNCDATA	$2, gclocals·ebb0e8ce1793da18f0378b883cb3e122(SB)
	0x000e 00014 (main.go:32)	FUNCDATA	$3, "".StringToBytes.stkobj(SB)
	0x000e 00014 (main.go:34)	PCDATA	$0, $0
	0x000e 00014 (main.go:34)	PCDATA	$1, $0
	0x000e 00014 (main.go:34)	XORPS	X0, X0
	0x0011 00017 (main.go:34)	MOVUPS	X0, "".bytesHeader(SP)
	0x0015 00021 (main.go:34)	MOVQ	$0, "".bytesHeader+16(SP)
	0x001e 00030 (main.go:35)	MOVQ	"".s+40(SP), AX
	0x0023 00035 (main.go:35)	MOVQ	AX, "".bytesHeader(SP)
	0x0027 00039 (main.go:36)	MOVQ	"".s+48(SP), AX
	0x002c 00044 (main.go:36)	MOVQ	AX, "".bytesHeader+16(SP)
	0x0031 00049 (main.go:37)	PCDATA	$1, $1
	0x0031 00049 (main.go:37)	MOVQ	"".s+48(SP), CX
	0x0036 00054 (main.go:37)	MOVQ	CX, "".bytesHeader+8(SP)
	0x003b 00059 (main.go:39)	PCDATA	$0, $1
	0x003b 00059 (main.go:39)	MOVQ	"".bytesHeader(SP), DX
	0x003f 00063 (main.go:39)	PCDATA	$0, $0
	0x003f 00063 (main.go:39)	PCDATA	$1, $2
	0x003f 00063 (main.go:39)	MOVQ	DX, "".~r1+56(SP)
	0x0044 00068 (main.go:39)	MOVQ	CX, "".~r1+64(SP)
	0x0049 00073 (main.go:39)	MOVQ	AX, "".~r1+72(SP)
	0x004e 00078 (main.go:39)	MOVQ	24(SP), BP
	0x0053 00083 (main.go:39)	ADDQ	$32, SP
	0x0057 00087 (main.go:39)	RET
	0x0000 48 83 ec 20 48 89 6c 24 18 48 8d 6c 24 18 0f 57  H.. H.l$.H.l$..W
	0x0010 c0 0f 11 04 24 48 c7 44 24 10 00 00 00 00 48 8b  ....$H.D$.....H.
	0x0020 44 24 28 48 89 04 24 48 8b 44 24 30 48 89 44 24  D$(H..$H.D$0H.D$
	0x0030 10 48 8b 4c 24 30 48 89 4c 24 08 48 8b 14 24 48  .H.L$0H.L$.H..$H
	0x0040 89 54 24 38 48 89 4c 24 40 48 89 44 24 48 48 8b  .T$8H.L$@H.D$HH.
	0x0050 6c 24 18 48 83 c4 20 c3                          l$.H.. .
"".GetBytes STEXT size=791 args=0x18 locals=0x180
	0x0000 00000 (main.go:42)	TEXT	"".GetBytes(SB), ABIInternal, $384-24
	0x0000 00000 (main.go:42)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:42)	LEAQ	-256(SP), AX
	0x0011 00017 (main.go:42)	CMPQ	AX, 16(CX)
	0x0015 00021 (main.go:42)	JLS	781
	0x001b 00027 (main.go:42)	SUBQ	$384, SP
	0x0022 00034 (main.go:42)	MOVQ	BP, 376(SP)
	0x002a 00042 (main.go:42)	LEAQ	376(SP), BP
	0x0032 00050 (main.go:42)	FUNCDATA	$0, gclocals·4dea565f520afaadcafa547fa021b9b7(SB)
	0x0032 00050 (main.go:42)	FUNCDATA	$1, gclocals·0ab7ac59bd0f2fcbe06e59c253658797(SB)
	0x0032 00050 (main.go:42)	FUNCDATA	$2, gclocals·7a658a2e7258b83e869501a01ac51f46(SB)
	0x0032 00050 (main.go:42)	FUNCDATA	$3, "".GetBytes.stkobj(SB)
	0x0032 00050 (main.go:43)	PCDATA	$0, $0
	0x0032 00050 (main.go:43)	PCDATA	$1, $0
	0x0032 00050 (<unknown line number>)	NOP
	0x0032 00050 (main.go:43)	PCDATA	$0, $1
	0x0032 00050 (main.go:43)	LEAQ	type.strings.Reader(SB), AX
	0x0039 00057 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $0
	0x0039 00057 ($GOROOT/src/strings/reader.go:154)	MOVQ	AX, (SP)
	0x003d 00061 ($GOROOT/src/strings/reader.go:154)	CALL	runtime.newobject(SB)
	0x0042 00066 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $2
	0x0042 00066 ($GOROOT/src/strings/reader.go:154)	MOVQ	8(SP), DI
	0x0047 00071 ($GOROOT/src/strings/reader.go:154)	MOVQ	$9, 8(DI)
	0x004f 00079 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $-2
	0x004f 00079 ($GOROOT/src/strings/reader.go:154)	PCDATA	$1, $-2
	0x004f 00079 ($GOROOT/src/strings/reader.go:154)	CMPL	runtime.writeBarrier(SB), $0
	0x0056 00086 ($GOROOT/src/strings/reader.go:154)	JNE	764
	0x005c 00092 ($GOROOT/src/strings/reader.go:154)	LEAQ	go.string."hello!123"(SB), AX
	0x0063 00099 ($GOROOT/src/strings/reader.go:154)	MOVQ	AX, (DI)
	0x0066 00102 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $2
	0x0066 00102 ($GOROOT/src/strings/reader.go:154)	PCDATA	$1, $1
	0x0066 00102 ($GOROOT/src/strings/reader.go:154)	MOVQ	DI, ""..autotmp_84+160(SP)
	0x006e 00110 ($GOROOT/src/strings/reader.go:154)	MOVQ	$0, 16(DI)
	0x0076 00118 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $0
	0x0076 00118 ($GOROOT/src/strings/reader.go:154)	MOVQ	$-1, 24(DI)
	0x007e 00126 (<unknown line number>)	NOP
	0x007e 00126 ($GOROOT/src/bufio/bufio.go:62)	XCHGL	AX, AX
	0x007f 00127 ($GOROOT/src/bufio/bufio.go:55)	PCDATA	$1, $2
	0x007f 00127 ($GOROOT/src/bufio/bufio.go:55)	MOVQ	$0, ""..autotmp_43+288(SP)
	0x008b 00139 ($GOROOT/src/bufio/bufio.go:55)	PCDATA	$0, $2
	0x008b 00139 ($GOROOT/src/bufio/bufio.go:55)	LEAQ	""..autotmp_43+296(SP), DI
	0x0093 00147 ($GOROOT/src/bufio/bufio.go:55)	XORPS	X0, X0
	0x0096 00150 ($GOROOT/src/bufio/bufio.go:55)	PCDATA	$0, $0
	0x0096 00150 ($GOROOT/src/bufio/bufio.go:55)	LEAQ	-48(DI), DI
	0x009a 00154 ($GOROOT/src/bufio/bufio.go:55)	DUFFZERO	$277
	0x00ad 00173 ($GOROOT/src/bufio/bufio.go:56)	PCDATA	$0, $3
	0x00ad 00173 ($GOROOT/src/bufio/bufio.go:56)	LEAQ	type.uint8(SB), CX
	0x00b4 00180 ($GOROOT/src/bufio/bufio.go:56)	PCDATA	$0, $0
	0x00b4 00180 ($GOROOT/src/bufio/bufio.go:56)	MOVQ	CX, (SP)
	0x00b8 00184 ($GOROOT/src/bufio/bufio.go:56)	MOVQ	$4096, 8(SP)
	0x00c1 00193 ($GOROOT/src/bufio/bufio.go:56)	MOVQ	$4096, 16(SP)
	0x00ca 00202 ($GOROOT/src/bufio/bufio.go:56)	CALL	runtime.makeslice(SB)
	0x00cf 00207 ($GOROOT/src/bufio/bufio.go:56)	PCDATA	$0, $1
	0x00cf 00207 ($GOROOT/src/bufio/bufio.go:56)	MOVQ	24(SP), AX
	0x00d4 00212 (<unknown line number>)	NOP
	0x00d4 00212 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$1, $3
	0x00d4 00212 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	$0, ""..autotmp_44+200(SP)
	0x00e0 00224 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $4
	0x00e0 00224 ($GOROOT/src/bufio/bufio.go:75)	LEAQ	""..autotmp_44+208(SP), DI
	0x00e8 00232 ($GOROOT/src/bufio/bufio.go:75)	XORPS	X0, X0
	0x00eb 00235 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $1
	0x00eb 00235 ($GOROOT/src/bufio/bufio.go:75)	LEAQ	-48(DI), DI
	0x00ef 00239 ($GOROOT/src/bufio/bufio.go:75)	DUFFZERO	$277
	0x0102 00258 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $0
	0x0102 00258 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	AX, ""..autotmp_44+200(SP)
	0x010a 00266 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	$4096, ""..autotmp_44+208(SP)
	0x0116 00278 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	$4096, ""..autotmp_44+216(SP)
	0x0122 00290 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $1
	0x0122 00290 ($GOROOT/src/bufio/bufio.go:75)	LEAQ	go.itab.*strings.Reader,io.Reader(SB), AX
	0x0129 00297 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $0
	0x0129 00297 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	AX, ""..autotmp_44+224(SP)
	0x0131 00305 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $1
	0x0131 00305 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$1, $4
	0x0131 00305 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	""..autotmp_84+160(SP), AX
	0x0139 00313 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $0
	0x0139 00313 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	AX, ""..autotmp_44+232(SP)
	0x0141 00321 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	$-1, ""..autotmp_44+272(SP)
	0x014d 00333 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	$-1, ""..autotmp_44+280(SP)
	0x0159 00345 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	""..autotmp_44+200(SP), AX
	0x0161 00353 ($GOROOT/src/bufio/bufio.go:75)	MOVQ	AX, ""..autotmp_43+288(SP)
	0x0169 00361 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $2
	0x0169 00361 ($GOROOT/src/bufio/bufio.go:75)	LEAQ	""..autotmp_43+296(SP), DI
	0x0171 00369 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $5
	0x0171 00369 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$1, $5
	0x0171 00369 ($GOROOT/src/bufio/bufio.go:75)	LEAQ	""..autotmp_44+208(SP), SI
	0x0179 00377 ($GOROOT/src/bufio/bufio.go:75)	PCDATA	$0, $0
	0x0179 00377 ($GOROOT/src/bufio/bufio.go:75)	DUFFCOPY	$826
	0x018c 00396 (main.go:44)	XCHGL	AX, AX
	0x018d 00397 ($GOROOT/src/bufio/bufio.go:477)	PCDATA	$0, $1
	0x018d 00397 ($GOROOT/src/bufio/bufio.go:477)	PCDATA	$1, $0
	0x018d 00397 ($GOROOT/src/bufio/bufio.go:477)	LEAQ	""..autotmp_43+288(SP), AX
	0x0195 00405 ($GOROOT/src/bufio/bufio.go:477)	PCDATA	$0, $0
	0x0195 00405 ($GOROOT/src/bufio/bufio.go:477)	MOVQ	AX, (SP)
	0x0199 00409 ($GOROOT/src/bufio/bufio.go:477)	MOVB	$10, 8(SP)
	0x019e 00414 ($GOROOT/src/bufio/bufio.go:477)	CALL	bufio.(*Reader).ReadBytes(SB)
	0x01a3 00419 ($GOROOT/src/bufio/bufio.go:477)	MOVQ	32(SP), AX
	0x01a8 00424 ($GOROOT/src/bufio/bufio.go:477)	MOVQ	24(SP), CX
	0x01ad 00429 ($GOROOT/src/bufio/bufio.go:477)	PCDATA	$0, $6
	0x01ad 00429 ($GOROOT/src/bufio/bufio.go:477)	MOVQ	16(SP), DX
	0x01b2 00434 ($GOROOT/src/bufio/bufio.go:478)	PCDATA	$0, $7
	0x01b2 00434 ($GOROOT/src/bufio/bufio.go:478)	LEAQ	""..autotmp_47+120(SP), BX
	0x01b7 00439 ($GOROOT/src/bufio/bufio.go:478)	PCDATA	$0, $6
	0x01b7 00439 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	BX, (SP)
	0x01bb 00443 ($GOROOT/src/bufio/bufio.go:478)	PCDATA	$0, $0
	0x01bb 00443 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	DX, 8(SP)
	0x01c0 00448 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	CX, 16(SP)
	0x01c5 00453 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	AX, 24(SP)
	0x01ca 00458 ($GOROOT/src/bufio/bufio.go:478)	CALL	runtime.slicebytetostring(SB)
	0x01cf 00463 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	40(SP), AX
	0x01d4 00468 ($GOROOT/src/bufio/bufio.go:478)	PCDATA	$0, $3
	0x01d4 00468 ($GOROOT/src/bufio/bufio.go:478)	MOVQ	32(SP), CX
	0x01d9 00473 (main.go:45)	PCDATA	$0, $0
	0x01d9 00473 (main.go:45)	PCDATA	$1, $6
	0x01d9 00473 (main.go:45)	MOVQ	CX, "".s+168(SP)
	0x01e1 00481 (main.go:45)	MOVQ	AX, "".s+176(SP)
	0x01e9 00489 (<unknown line number>)	NOP
	0x01e9 00489 (main.go:34)	XORPS	X1, X1
	0x01ec 00492 (main.go:34)	MOVUPS	X1, "".bytesHeader+96(SP)
	0x01f1 00497 (main.go:34)	MOVQ	$0, "".bytesHeader+112(SP)
	0x01fa 00506 (main.go:35)	MOVQ	"".s+168(SP), AX
	0x0202 00514 (main.go:35)	MOVQ	AX, "".bytesHeader+96(SP)
	0x0207 00519 (main.go:36)	MOVQ	"".s+176(SP), AX
	0x020f 00527 (main.go:36)	MOVQ	AX, ""..autotmp_85+88(SP)
	0x0214 00532 (main.go:36)	MOVQ	AX, "".bytesHeader+112(SP)
	0x0219 00537 (main.go:37)	PCDATA	$1, $0
	0x0219 00537 (main.go:37)	MOVQ	"".s+176(SP), CX
	0x0221 00545 (main.go:37)	MOVQ	CX, ""..autotmp_86+80(SP)
	0x0226 00550 (main.go:37)	MOVQ	CX, "".bytesHeader+104(SP)
	0x022b 00555 (main.go:39)	PCDATA	$0, $6
	0x022b 00555 (main.go:39)	MOVQ	"".bytesHeader+96(SP), DX
	0x0230 00560 (main.go:39)	PCDATA	$1, $7
	0x0230 00560 (main.go:39)	MOVQ	DX, "".out.ptr+152(SP)
	0x0238 00568 (main.go:46)	PCDATA	$0, $0
	0x0238 00568 (main.go:46)	MOVQ	DX, (SP)
	0x023c 00572 (main.go:46)	MOVQ	CX, 8(SP)
	0x0241 00577 (main.go:46)	MOVQ	AX, 16(SP)
	0x0246 00582 (main.go:46)	CALL	runtime.convTslice(SB)
	0x024b 00587 (main.go:46)	PCDATA	$0, $1
	0x024b 00587 (main.go:46)	MOVQ	24(SP), AX
	0x0250 00592 (main.go:46)	PCDATA	$1, $8
	0x0250 00592 (main.go:46)	XORPS	X1, X1
	0x0253 00595 (main.go:46)	MOVUPS	X1, ""..autotmp_54+184(SP)
	0x025b 00603 (main.go:46)	PCDATA	$0, $8
	0x025b 00603 (main.go:46)	LEAQ	type.[]uint8(SB), CX
	0x0262 00610 (main.go:46)	PCDATA	$0, $1
	0x0262 00610 (main.go:46)	MOVQ	CX, ""..autotmp_54+184(SP)
	0x026a 00618 (main.go:46)	PCDATA	$0, $0
	0x026a 00618 (main.go:46)	MOVQ	AX, ""..autotmp_54+192(SP)
	0x0272 00626 (<unknown line number>)	NOP
	0x0272 00626 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x0272 00626 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x0279 00633 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $8
	0x0279 00633 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x0280 00640 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x0280 00640 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x0284 00644 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x0284 00644 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x0289 00649 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x0289 00649 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.string."GetBytes: %s\n"(SB), AX
	0x0290 00656 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x0290 00656 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x0295 00661 ($GOROOT/src/fmt/print.go:213)	MOVQ	$13, 24(SP)
	0x029e 00670 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x029e 00670 ($GOROOT/src/fmt/print.go:213)	PCDATA	$1, $7
	0x029e 00670 ($GOROOT/src/fmt/print.go:213)	LEAQ	""..autotmp_54+184(SP), AX
	0x02a6 00678 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x02a6 00678 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x02ab 00683 ($GOROOT/src/fmt/print.go:213)	MOVQ	$1, 40(SP)
	0x02b4 00692 ($GOROOT/src/fmt/print.go:213)	MOVQ	$1, 48(SP)
	0x02bd 00701 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x02c2 00706 (main.go:48)	PCDATA	$0, $1
	0x02c2 00706 (main.go:48)	PCDATA	$1, $9
	0x02c2 00706 (main.go:48)	MOVQ	"".out.ptr+152(SP), AX
	0x02ca 00714 (main.go:48)	PCDATA	$0, $0
	0x02ca 00714 (main.go:48)	MOVQ	AX, "".~r0+392(SP)
	0x02d2 00722 (main.go:48)	MOVQ	""..autotmp_86+80(SP), AX
	0x02d7 00727 (main.go:48)	MOVQ	AX, "".~r0+400(SP)
	0x02df 00735 (main.go:48)	MOVQ	""..autotmp_85+88(SP), AX
	0x02e4 00740 (main.go:48)	MOVQ	AX, "".~r0+408(SP)
	0x02ec 00748 (main.go:48)	MOVQ	376(SP), BP
	0x02f4 00756 (main.go:48)	ADDQ	$384, SP
	0x02fb 00763 (main.go:48)	RET
	0x02fc 00764 ($GOROOT/src/strings/reader.go:154)	PCDATA	$0, $-2
	0x02fc 00764 ($GOROOT/src/strings/reader.go:154)	PCDATA	$1, $-2
	0x02fc 00764 ($GOROOT/src/strings/reader.go:154)	LEAQ	go.string."hello!123"(SB), AX
	0x0303 00771 ($GOROOT/src/strings/reader.go:154)	CALL	runtime.gcWriteBarrier(SB)
	0x0308 00776 ($GOROOT/src/strings/reader.go:154)	JMP	102
	0x030d 00781 ($GOROOT/src/strings/reader.go:154)	NOP
	0x030d 00781 (main.go:42)	PCDATA	$1, $-1
	0x030d 00781 (main.go:42)	PCDATA	$0, $-1
	0x030d 00781 (main.go:42)	CALL	runtime.morestack_noctxt(SB)
	0x0312 00786 (main.go:42)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 8d 84 24 00 ff ff  dH..%....H..$...
	0x0010 ff 48 3b 41 10 0f 86 f2 02 00 00 48 81 ec 80 01  .H;A.......H....
	0x0020 00 00 48 89 ac 24 78 01 00 00 48 8d ac 24 78 01  ..H..$x...H..$x.
	0x0030 00 00 48 8d 05 00 00 00 00 48 89 04 24 e8 00 00  ..H......H..$...
	0x0040 00 00 48 8b 7c 24 08 48 c7 47 08 09 00 00 00 83  ..H.|$.H.G......
	0x0050 3d 00 00 00 00 00 0f 85 a0 02 00 00 48 8d 05 00  =...........H...
	0x0060 00 00 00 48 89 07 48 89 bc 24 a0 00 00 00 48 c7  ...H..H..$....H.
	0x0070 47 10 00 00 00 00 48 c7 47 18 ff ff ff ff 90 48  G.....H.G......H
	0x0080 c7 84 24 20 01 00 00 00 00 00 00 48 8d bc 24 28  ..$ .......H..$(
	0x0090 01 00 00 0f 57 c0 48 8d 7f d0 48 89 6c 24 f0 48  ....W.H...H.l$.H
	0x00a0 8d 6c 24 f0 e8 00 00 00 00 48 8b 6d 00 48 8d 0d  .l$......H.m.H..
	0x00b0 00 00 00 00 48 89 0c 24 48 c7 44 24 08 00 10 00  ....H..$H.D$....
	0x00c0 00 48 c7 44 24 10 00 10 00 00 e8 00 00 00 00 48  .H.D$..........H
	0x00d0 8b 44 24 18 48 c7 84 24 c8 00 00 00 00 00 00 00  .D$.H..$........
	0x00e0 48 8d bc 24 d0 00 00 00 0f 57 c0 48 8d 7f d0 48  H..$.....W.H...H
	0x00f0 89 6c 24 f0 48 8d 6c 24 f0 e8 00 00 00 00 48 8b  .l$.H.l$......H.
	0x0100 6d 00 48 89 84 24 c8 00 00 00 48 c7 84 24 d0 00  m.H..$....H..$..
	0x0110 00 00 00 10 00 00 48 c7 84 24 d8 00 00 00 00 10  ......H..$......
	0x0120 00 00 48 8d 05 00 00 00 00 48 89 84 24 e0 00 00  ..H......H..$...
	0x0130 00 48 8b 84 24 a0 00 00 00 48 89 84 24 e8 00 00  .H..$....H..$...
	0x0140 00 48 c7 84 24 10 01 00 00 ff ff ff ff 48 c7 84  .H..$........H..
	0x0150 24 18 01 00 00 ff ff ff ff 48 8b 84 24 c8 00 00  $........H..$...
	0x0160 00 48 89 84 24 20 01 00 00 48 8d bc 24 28 01 00  .H..$ ...H..$(..
	0x0170 00 48 8d b4 24 d0 00 00 00 48 89 6c 24 f0 48 8d  .H..$....H.l$.H.
	0x0180 6c 24 f0 e8 00 00 00 00 48 8b 6d 00 90 48 8d 84  l$......H.m..H..
	0x0190 24 20 01 00 00 48 89 04 24 c6 44 24 08 0a e8 00  $ ...H..$.D$....
	0x01a0 00 00 00 48 8b 44 24 20 48 8b 4c 24 18 48 8b 54  ...H.D$ H.L$.H.T
	0x01b0 24 10 48 8d 5c 24 78 48 89 1c 24 48 89 54 24 08  $.H.\$xH..$H.T$.
	0x01c0 48 89 4c 24 10 48 89 44 24 18 e8 00 00 00 00 48  H.L$.H.D$......H
	0x01d0 8b 44 24 28 48 8b 4c 24 20 48 89 8c 24 a8 00 00  .D$(H.L$ H..$...
	0x01e0 00 48 89 84 24 b0 00 00 00 0f 57 c9 0f 11 4c 24  .H..$.....W...L$
	0x01f0 60 48 c7 44 24 70 00 00 00 00 48 8b 84 24 a8 00  `H.D$p....H..$..
	0x0200 00 00 48 89 44 24 60 48 8b 84 24 b0 00 00 00 48  ..H.D$`H..$....H
	0x0210 89 44 24 58 48 89 44 24 70 48 8b 8c 24 b0 00 00  .D$XH.D$pH..$...
	0x0220 00 48 89 4c 24 50 48 89 4c 24 68 48 8b 54 24 60  .H.L$PH.L$hH.T$`
	0x0230 48 89 94 24 98 00 00 00 48 89 14 24 48 89 4c 24  H..$....H..$H.L$
	0x0240 08 48 89 44 24 10 e8 00 00 00 00 48 8b 44 24 18  .H.D$......H.D$.
	0x0250 0f 57 c9 0f 11 8c 24 b8 00 00 00 48 8d 0d 00 00  .W....$....H....
	0x0260 00 00 48 89 8c 24 b8 00 00 00 48 89 84 24 c0 00  ..H..$....H..$..
	0x0270 00 00 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00  ..H......H......
	0x0280 48 89 0c 24 48 89 44 24 08 48 8d 05 00 00 00 00  H..$H.D$.H......
	0x0290 48 89 44 24 10 48 c7 44 24 18 0d 00 00 00 48 8d  H.D$.H.D$.....H.
	0x02a0 84 24 b8 00 00 00 48 89 44 24 20 48 c7 44 24 28  .$....H.D$ H.D$(
	0x02b0 01 00 00 00 48 c7 44 24 30 01 00 00 00 e8 00 00  ....H.D$0.......
	0x02c0 00 00 48 8b 84 24 98 00 00 00 48 89 84 24 88 01  ..H..$....H..$..
	0x02d0 00 00 48 8b 44 24 50 48 89 84 24 90 01 00 00 48  ..H.D$PH..$....H
	0x02e0 8b 44 24 58 48 89 84 24 98 01 00 00 48 8b ac 24  .D$XH..$....H..$
	0x02f0 78 01 00 00 48 81 c4 80 01 00 00 c3 48 8d 05 00  x...H.......H...
	0x0300 00 00 00 e8 00 00 00 00 e9 59 fd ff ff e8 00 00  .........Y......
	0x0310 00 00 e9 e9 fc ff ff                             .......
	rel 5+4 t=16 TLS+0
	rel 53+4 t=15 type.strings.Reader+0
	rel 62+4 t=8 runtime.newobject+0
	rel 81+4 t=15 runtime.writeBarrier+-1
	rel 95+4 t=15 go.string."hello!123"+0
	rel 165+4 t=8 runtime.duffzero+277
	rel 176+4 t=15 type.uint8+0
	rel 203+4 t=8 runtime.makeslice+0
	rel 250+4 t=8 runtime.duffzero+277
	rel 293+4 t=15 go.itab.*strings.Reader,io.Reader+0
	rel 388+4 t=8 runtime.duffcopy+826
	rel 415+4 t=8 bufio.(*Reader).ReadBytes+0
	rel 459+4 t=8 runtime.slicebytetostring+0
	rel 583+4 t=8 runtime.convTslice+0
	rel 606+4 t=15 type.[]uint8+0
	rel 629+4 t=15 os.Stdout+0
	rel 636+4 t=15 go.itab.*os.File,io.Writer+0
	rel 652+4 t=15 go.string."GetBytes: %s\n"+0
	rel 702+4 t=8 fmt.Fprintf+0
	rel 767+4 t=15 go.string."hello!123"+0
	rel 772+4 t=8 runtime.gcWriteBarrier+0
	rel 782+4 t=8 runtime.morestack_noctxt+0
"".UnsafeDefinition STEXT size=228 args=0x8 locals=0x60
	0x0000 00000 (main.go:51)	TEXT	"".UnsafeDefinition(SB), ABIInternal, $96-8
	0x0000 00000 (main.go:51)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:51)	CMPQ	SP, 16(CX)
	0x000d 00013 (main.go:51)	JLS	218
	0x0013 00019 (main.go:51)	SUBQ	$96, SP
	0x0017 00023 (main.go:51)	MOVQ	BP, 88(SP)
	0x001c 00028 (main.go:51)	LEAQ	88(SP), BP
	0x0021 00033 (main.go:51)	FUNCDATA	$0, gclocals·a5055cd68876ca89b660e46f7e21fd17(SB)
	0x0021 00033 (main.go:51)	FUNCDATA	$1, gclocals·4ef8357644ec89b6336b31bfc1bf9954(SB)
	0x0021 00033 (main.go:51)	FUNCDATA	$2, gclocals·ba192201ac73f95fb90b551d9176d705(SB)
	0x0021 00033 (main.go:51)	FUNCDATA	$3, "".UnsafeDefinition.stkobj(SB)
	0x0021 00033 (main.go:53)	PCDATA	$0, $1
	0x0021 00033 (main.go:53)	PCDATA	$1, $0
	0x0021 00033 (main.go:53)	LEAQ	type.int(SB), AX
	0x0028 00040 (main.go:53)	PCDATA	$0, $0
	0x0028 00040 (main.go:53)	MOVQ	AX, (SP)
	0x002c 00044 (main.go:53)	CALL	runtime.newobject(SB)
	0x0031 00049 (main.go:53)	PCDATA	$0, $1
	0x0031 00049 (main.go:53)	MOVQ	8(SP), AX
	0x0036 00054 (main.go:53)	PCDATA	$0, $0
	0x0036 00054 (main.go:53)	PCDATA	$1, $1
	0x0036 00054 (main.go:53)	MOVQ	AX, "".&y+64(SP)
	0x003b 00059 (<unknown line number>)	NOP
	0x003b 00059 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $2
	0x003b 00059 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	math/rand.globalRand(SB), CX
	0x0042 00066 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $0
	0x0042 00066 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	CX, (SP)
	0x0046 00070 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	$100, 8(SP)
	0x004f 00079 ($GOROOT/src/math/rand/rand.go:329)	CALL	math/rand.(*Rand).Intn(SB)
	0x0054 00084 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	16(SP), AX
	0x0059 00089 (main.go:53)	PCDATA	$0, $2
	0x0059 00089 (main.go:53)	MOVQ	"".&y+64(SP), CX
	0x005e 00094 (main.go:53)	PCDATA	$0, $0
	0x005e 00094 (main.go:53)	MOVQ	AX, (CX)
	0x0061 00097 (main.go:55)	CALL	"".UnsafeCall(SB)
	0x0066 00102 (main.go:55)	CMPB	(SP), $0
	0x006a 00106 (main.go:55)	JNE	128
	0x006c 00108 (main.go:58)	PCDATA	$0, $1
	0x006c 00108 (main.go:58)	PCDATA	$1, $0
	0x006c 00108 (main.go:58)	MOVQ	"".&y+64(SP), AX
	0x0071 00113 (main.go:58)	PCDATA	$0, $0
	0x0071 00113 (main.go:58)	PCDATA	$1, $2
	0x0071 00113 (main.go:58)	MOVQ	AX, "".~r0+104(SP)
	0x0076 00118 (main.go:58)	MOVQ	88(SP), BP
	0x007b 00123 (main.go:58)	ADDQ	$96, SP
	0x007f 00127 (main.go:58)	RET
	0x0080 00128 (main.go:56)	PCDATA	$1, $3
	0x0080 00128 (main.go:56)	XORPS	X0, X0
	0x0083 00131 (main.go:56)	MOVUPS	X0, ""..autotmp_18+72(SP)
	0x0088 00136 (main.go:56)	PCDATA	$0, $1
	0x0088 00136 (main.go:56)	LEAQ	type.string(SB), AX
	0x008f 00143 (main.go:56)	PCDATA	$0, $0
	0x008f 00143 (main.go:56)	MOVQ	AX, ""..autotmp_18+72(SP)
	0x0094 00148 (main.go:56)	PCDATA	$0, $1
	0x0094 00148 (main.go:56)	LEAQ	""..stmp_0(SB), AX
	0x009b 00155 (main.go:56)	PCDATA	$0, $0
	0x009b 00155 (main.go:56)	MOVQ	AX, ""..autotmp_18+80(SP)
	0x00a0 00160 (<unknown line number>)	NOP
	0x00a0 00160 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00a0 00160 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $3
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x00ae 00174 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00ae 00174 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x00b2 00178 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00b2 00178 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $1
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_18+72(SP), AX
	0x00bc 00188 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00bc 00188 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x00c1 00193 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x00ca 00202 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x00d3 00211 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x00d8 00216 (main.go:58)	JMP	108
	0x00da 00218 (main.go:58)	NOP
	0x00da 00218 (main.go:51)	PCDATA	$1, $-1
	0x00da 00218 (main.go:51)	PCDATA	$0, $-1
	0x00da 00218 (main.go:51)	CALL	runtime.morestack_noctxt(SB)
	0x00df 00223 (main.go:51)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 c7  dH..%....H;a....
	0x0010 00 00 00 48 83 ec 60 48 89 6c 24 58 48 8d 6c 24  ...H..`H.l$XH.l$
	0x0020 58 48 8d 05 00 00 00 00 48 89 04 24 e8 00 00 00  XH......H..$....
	0x0030 00 48 8b 44 24 08 48 89 44 24 40 48 8b 0d 00 00  .H.D$.H.D$@H....
	0x0040 00 00 48 89 0c 24 48 c7 44 24 08 64 00 00 00 e8  ..H..$H.D$.d....
	0x0050 00 00 00 00 48 8b 44 24 10 48 8b 4c 24 40 48 89  ....H.D$.H.L$@H.
	0x0060 01 e8 00 00 00 00 80 3c 24 00 75 14 48 8b 44 24  .......<$.u.H.D$
	0x0070 40 48 89 44 24 68 48 8b 6c 24 58 48 83 c4 60 c3  @H.D$hH.l$XH..`.
	0x0080 0f 57 c0 0f 11 44 24 48 48 8d 05 00 00 00 00 48  .W...D$HH......H
	0x0090 89 44 24 48 48 8d 05 00 00 00 00 48 89 44 24 50  .D$HH......H.D$P
	0x00a0 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48 89  H......H......H.
	0x00b0 0c 24 48 89 44 24 08 48 8d 44 24 48 48 89 44 24  .$H.D$.H.D$HH.D$
	0x00c0 10 48 c7 44 24 18 01 00 00 00 48 c7 44 24 20 01  .H.D$.....H.D$ .
	0x00d0 00 00 00 e8 00 00 00 00 eb 92 e8 00 00 00 00 e9  ................
	0x00e0 1c ff ff ff                                      ....
	rel 5+4 t=16 TLS+0
	rel 36+4 t=15 type.int+0
	rel 45+4 t=8 runtime.newobject+0
	rel 62+4 t=15 math/rand.globalRand+0
	rel 80+4 t=8 math/rand.(*Rand).Intn+0
	rel 98+4 t=8 "".UnsafeCall+0
	rel 139+4 t=15 type.string+0
	rel 151+4 t=15 ""..stmp_0+0
	rel 163+4 t=15 os.Stdout+0
	rel 170+4 t=15 go.itab.*os.File,io.Writer+0
	rel 212+4 t=8 fmt.Fprintln+0
	rel 219+4 t=8 runtime.morestack_noctxt+0
"".UnsafeParameter STEXT size=207 args=0x10 locals=0x60
	0x0000 00000 (main.go:61)	TEXT	"".UnsafeParameter(SB), ABIInternal, $96-16
	0x0000 00000 (main.go:61)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:61)	CMPQ	SP, 16(CX)
	0x000d 00013 (main.go:61)	JLS	197
	0x0013 00019 (main.go:61)	SUBQ	$96, SP
	0x0017 00023 (main.go:61)	MOVQ	BP, 88(SP)
	0x001c 00028 (main.go:61)	LEAQ	88(SP), BP
	0x0021 00033 (main.go:61)	FUNCDATA	$0, gclocals·1ff8b8d8bc8134ef1359e077847f1272(SB)
	0x0021 00033 (main.go:61)	FUNCDATA	$1, gclocals·ffd148479e14c29ee3c68361945c5d25(SB)
	0x0021 00033 (main.go:61)	FUNCDATA	$2, gclocals·ba192201ac73f95fb90b551d9176d705(SB)
	0x0021 00033 (main.go:61)	FUNCDATA	$3, "".UnsafeParameter.stkobj(SB)
	0x0021 00033 (main.go:62)	PCDATA	$0, $0
	0x0021 00033 (main.go:62)	PCDATA	$1, $0
	0x0021 00033 (<unknown line number>)	NOP
	0x0021 00033 (main.go:62)	PCDATA	$0, $1
	0x0021 00033 (main.go:62)	MOVQ	math/rand.globalRand(SB), AX
	0x0028 00040 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $0
	0x0028 00040 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	AX, (SP)
	0x002c 00044 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	$100, 8(SP)
	0x0035 00053 ($GOROOT/src/math/rand/rand.go:329)	CALL	math/rand.(*Rand).Intn(SB)
	0x003a 00058 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	16(SP), AX
	0x003f 00063 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	AX, "".y+64(SP)
	0x0044 00068 (main.go:63)	CALL	"".UnsafeCall(SB)
	0x0049 00073 (main.go:63)	CMPB	(SP), $0
	0x004d 00077 (main.go:63)	JNE	107
	0x004f 00079 (main.go:66)	MOVQ	"".y+64(SP), AX
	0x0054 00084 (main.go:66)	PCDATA	$0, $2
	0x0054 00084 (main.go:66)	PCDATA	$1, $1
	0x0054 00084 (main.go:66)	MOVQ	"".x+104(SP), CX
	0x0059 00089 (main.go:66)	PCDATA	$0, $0
	0x0059 00089 (main.go:66)	ADDQ	(CX), AX
	0x005c 00092 (main.go:66)	MOVQ	AX, "".~r1+112(SP)
	0x0061 00097 (main.go:66)	MOVQ	88(SP), BP
	0x0066 00102 (main.go:66)	ADDQ	$96, SP
	0x006a 00106 (main.go:66)	RET
	0x006b 00107 (main.go:64)	PCDATA	$1, $2
	0x006b 00107 (main.go:64)	XORPS	X0, X0
	0x006e 00110 (main.go:64)	MOVUPS	X0, ""..autotmp_17+72(SP)
	0x0073 00115 (main.go:64)	PCDATA	$0, $1
	0x0073 00115 (main.go:64)	LEAQ	type.string(SB), AX
	0x007a 00122 (main.go:64)	PCDATA	$0, $0
	0x007a 00122 (main.go:64)	MOVQ	AX, ""..autotmp_17+72(SP)
	0x007f 00127 (main.go:64)	PCDATA	$0, $1
	0x007f 00127 (main.go:64)	LEAQ	""..stmp_1(SB), AX
	0x0086 00134 (main.go:64)	PCDATA	$0, $0
	0x0086 00134 (main.go:64)	MOVQ	AX, ""..autotmp_17+80(SP)
	0x008b 00139 (<unknown line number>)	NOP
	0x008b 00139 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x008b 00139 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x0092 00146 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $3
	0x0092 00146 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x0099 00153 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x0099 00153 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x009d 00157 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x009d 00157 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x00a2 00162 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00a2 00162 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $0
	0x00a2 00162 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_17+72(SP), AX
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x00ac 00172 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x00b5 00181 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x00be 00190 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x00c3 00195 (main.go:66)	JMP	79
	0x00c5 00197 (main.go:66)	NOP
	0x00c5 00197 (main.go:61)	PCDATA	$1, $-1
	0x00c5 00197 (main.go:61)	PCDATA	$0, $-1
	0x00c5 00197 (main.go:61)	CALL	runtime.morestack_noctxt(SB)
	0x00ca 00202 (main.go:61)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 b2  dH..%....H;a....
	0x0010 00 00 00 48 83 ec 60 48 89 6c 24 58 48 8d 6c 24  ...H..`H.l$XH.l$
	0x0020 58 48 8b 05 00 00 00 00 48 89 04 24 48 c7 44 24  XH......H..$H.D$
	0x0030 08 64 00 00 00 e8 00 00 00 00 48 8b 44 24 10 48  .d........H.D$.H
	0x0040 89 44 24 40 e8 00 00 00 00 80 3c 24 00 75 1c 48  .D$@......<$.u.H
	0x0050 8b 44 24 40 48 8b 4c 24 68 48 03 01 48 89 44 24  .D$@H.L$hH..H.D$
	0x0060 70 48 8b 6c 24 58 48 83 c4 60 c3 0f 57 c0 0f 11  pH.l$XH..`..W...
	0x0070 44 24 48 48 8d 05 00 00 00 00 48 89 44 24 48 48  D$HH......H.D$HH
	0x0080 8d 05 00 00 00 00 48 89 44 24 50 48 8b 05 00 00  ......H.D$PH....
	0x0090 00 00 48 8d 0d 00 00 00 00 48 89 0c 24 48 89 44  ..H......H..$H.D
	0x00a0 24 08 48 8d 44 24 48 48 89 44 24 10 48 c7 44 24  $.H.D$HH.D$.H.D$
	0x00b0 18 01 00 00 00 48 c7 44 24 20 01 00 00 00 e8 00  .....H.D$ ......
	0x00c0 00 00 00 eb 8a e8 00 00 00 00 e9 31 ff ff ff     ...........1...
	rel 5+4 t=16 TLS+0
	rel 36+4 t=15 math/rand.globalRand+0
	rel 54+4 t=8 math/rand.(*Rand).Intn+0
	rel 69+4 t=8 "".UnsafeCall+0
	rel 118+4 t=15 type.string+0
	rel 130+4 t=15 ""..stmp_1+0
	rel 142+4 t=15 os.Stdout+0
	rel 149+4 t=15 go.itab.*os.File,io.Writer+0
	rel 191+4 t=8 fmt.Fprintln+0
	rel 198+4 t=8 runtime.morestack_noctxt+0
"".UnsafeAssignment STEXT size=228 args=0x8 locals=0x60
	0x0000 00000 (main.go:69)	TEXT	"".UnsafeAssignment(SB), ABIInternal, $96-8
	0x0000 00000 (main.go:69)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:69)	CMPQ	SP, 16(CX)
	0x000d 00013 (main.go:69)	JLS	218
	0x0013 00019 (main.go:69)	SUBQ	$96, SP
	0x0017 00023 (main.go:69)	MOVQ	BP, 88(SP)
	0x001c 00028 (main.go:69)	LEAQ	88(SP), BP
	0x0021 00033 (main.go:69)	FUNCDATA	$0, gclocals·a5055cd68876ca89b660e46f7e21fd17(SB)
	0x0021 00033 (main.go:69)	FUNCDATA	$1, gclocals·4ef8357644ec89b6336b31bfc1bf9954(SB)
	0x0021 00033 (main.go:69)	FUNCDATA	$2, gclocals·ba192201ac73f95fb90b551d9176d705(SB)
	0x0021 00033 (main.go:69)	FUNCDATA	$3, "".UnsafeAssignment.stkobj(SB)
	0x0021 00033 (main.go:70)	PCDATA	$0, $1
	0x0021 00033 (main.go:70)	PCDATA	$1, $0
	0x0021 00033 (main.go:70)	LEAQ	type.int(SB), AX
	0x0028 00040 (main.go:70)	PCDATA	$0, $0
	0x0028 00040 (main.go:70)	MOVQ	AX, (SP)
	0x002c 00044 (main.go:70)	CALL	runtime.newobject(SB)
	0x0031 00049 (main.go:70)	PCDATA	$0, $1
	0x0031 00049 (main.go:70)	MOVQ	8(SP), AX
	0x0036 00054 (main.go:70)	PCDATA	$0, $0
	0x0036 00054 (main.go:70)	PCDATA	$1, $1
	0x0036 00054 (main.go:70)	MOVQ	AX, ""..autotmp_24+64(SP)
	0x003b 00059 (<unknown line number>)	NOP
	0x003b 00059 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $2
	0x003b 00059 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	math/rand.globalRand(SB), CX
	0x0042 00066 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $0
	0x0042 00066 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	CX, (SP)
	0x0046 00070 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	$100, 8(SP)
	0x004f 00079 ($GOROOT/src/math/rand/rand.go:329)	CALL	math/rand.(*Rand).Intn(SB)
	0x0054 00084 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	16(SP), AX
	0x0059 00089 (main.go:70)	PCDATA	$0, $2
	0x0059 00089 (main.go:70)	MOVQ	""..autotmp_24+64(SP), CX
	0x005e 00094 (main.go:70)	PCDATA	$0, $0
	0x005e 00094 (main.go:70)	MOVQ	AX, (CX)
	0x0061 00097 (main.go:72)	CALL	"".UnsafeCall(SB)
	0x0066 00102 (main.go:72)	CMPB	(SP), $0
	0x006a 00106 (main.go:72)	JNE	128
	0x006c 00108 (main.go:75)	PCDATA	$0, $1
	0x006c 00108 (main.go:75)	PCDATA	$1, $0
	0x006c 00108 (main.go:75)	MOVQ	""..autotmp_24+64(SP), AX
	0x0071 00113 (main.go:75)	PCDATA	$0, $0
	0x0071 00113 (main.go:75)	PCDATA	$1, $2
	0x0071 00113 (main.go:75)	MOVQ	AX, "".~r0+104(SP)
	0x0076 00118 (main.go:75)	MOVQ	88(SP), BP
	0x007b 00123 (main.go:75)	ADDQ	$96, SP
	0x007f 00127 (main.go:75)	RET
	0x0080 00128 (main.go:73)	PCDATA	$1, $3
	0x0080 00128 (main.go:73)	XORPS	X0, X0
	0x0083 00131 (main.go:73)	MOVUPS	X0, ""..autotmp_18+72(SP)
	0x0088 00136 (main.go:73)	PCDATA	$0, $1
	0x0088 00136 (main.go:73)	LEAQ	type.string(SB), AX
	0x008f 00143 (main.go:73)	PCDATA	$0, $0
	0x008f 00143 (main.go:73)	MOVQ	AX, ""..autotmp_18+72(SP)
	0x0094 00148 (main.go:73)	PCDATA	$0, $1
	0x0094 00148 (main.go:73)	LEAQ	""..stmp_2(SB), AX
	0x009b 00155 (main.go:73)	PCDATA	$0, $0
	0x009b 00155 (main.go:73)	MOVQ	AX, ""..autotmp_18+80(SP)
	0x00a0 00160 (<unknown line number>)	NOP
	0x00a0 00160 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00a0 00160 ($GOROOT/src/fmt/print.go:274)	MOVQ	os.Stdout(SB), AX
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $3
	0x00a7 00167 ($GOROOT/src/fmt/print.go:274)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x00ae 00174 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00ae 00174 ($GOROOT/src/fmt/print.go:274)	MOVQ	CX, (SP)
	0x00b2 00178 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00b2 00178 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 8(SP)
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $1
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	PCDATA	$1, $1
	0x00b7 00183 ($GOROOT/src/fmt/print.go:274)	LEAQ	""..autotmp_18+72(SP), AX
	0x00bc 00188 ($GOROOT/src/fmt/print.go:274)	PCDATA	$0, $0
	0x00bc 00188 ($GOROOT/src/fmt/print.go:274)	MOVQ	AX, 16(SP)
	0x00c1 00193 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 24(SP)
	0x00ca 00202 ($GOROOT/src/fmt/print.go:274)	MOVQ	$1, 32(SP)
	0x00d3 00211 ($GOROOT/src/fmt/print.go:274)	CALL	fmt.Fprintln(SB)
	0x00d8 00216 (main.go:75)	JMP	108
	0x00da 00218 (main.go:75)	NOP
	0x00da 00218 (main.go:69)	PCDATA	$1, $-1
	0x00da 00218 (main.go:69)	PCDATA	$0, $-1
	0x00da 00218 (main.go:69)	CALL	runtime.morestack_noctxt(SB)
	0x00df 00223 (main.go:69)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 c7  dH..%....H;a....
	0x0010 00 00 00 48 83 ec 60 48 89 6c 24 58 48 8d 6c 24  ...H..`H.l$XH.l$
	0x0020 58 48 8d 05 00 00 00 00 48 89 04 24 e8 00 00 00  XH......H..$....
	0x0030 00 48 8b 44 24 08 48 89 44 24 40 48 8b 0d 00 00  .H.D$.H.D$@H....
	0x0040 00 00 48 89 0c 24 48 c7 44 24 08 64 00 00 00 e8  ..H..$H.D$.d....
	0x0050 00 00 00 00 48 8b 44 24 10 48 8b 4c 24 40 48 89  ....H.D$.H.L$@H.
	0x0060 01 e8 00 00 00 00 80 3c 24 00 75 14 48 8b 44 24  .......<$.u.H.D$
	0x0070 40 48 89 44 24 68 48 8b 6c 24 58 48 83 c4 60 c3  @H.D$hH.l$XH..`.
	0x0080 0f 57 c0 0f 11 44 24 48 48 8d 05 00 00 00 00 48  .W...D$HH......H
	0x0090 89 44 24 48 48 8d 05 00 00 00 00 48 89 44 24 50  .D$HH......H.D$P
	0x00a0 48 8b 05 00 00 00 00 48 8d 0d 00 00 00 00 48 89  H......H......H.
	0x00b0 0c 24 48 89 44 24 08 48 8d 44 24 48 48 89 44 24  .$H.D$.H.D$HH.D$
	0x00c0 10 48 c7 44 24 18 01 00 00 00 48 c7 44 24 20 01  .H.D$.....H.D$ .
	0x00d0 00 00 00 e8 00 00 00 00 eb 92 e8 00 00 00 00 e9  ................
	0x00e0 1c ff ff ff                                      ....
	rel 5+4 t=16 TLS+0
	rel 36+4 t=15 type.int+0
	rel 45+4 t=8 runtime.newobject+0
	rel 62+4 t=15 math/rand.globalRand+0
	rel 80+4 t=8 math/rand.(*Rand).Intn+0
	rel 98+4 t=8 "".UnsafeCall+0
	rel 139+4 t=15 type.string+0
	rel 151+4 t=15 ""..stmp_2+0
	rel 163+4 t=15 os.Stdout+0
	rel 170+4 t=15 go.itab.*os.File,io.Writer+0
	rel 212+4 t=8 fmt.Fprintln+0
	rel 219+4 t=8 runtime.morestack_noctxt+0
"".UnsafeCall STEXT size=100 args=0x8 locals=0x28
	0x0000 00000 (main.go:78)	TEXT	"".UnsafeCall(SB), ABIInternal, $40-8
	0x0000 00000 (main.go:78)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:78)	CMPQ	SP, 16(CX)
	0x000d 00013 (main.go:78)	JLS	93
	0x000f 00015 (main.go:78)	SUBQ	$40, SP
	0x0013 00019 (main.go:78)	MOVQ	BP, 32(SP)
	0x0018 00024 (main.go:78)	LEAQ	32(SP), BP
	0x001d 00029 (main.go:78)	FUNCDATA	$0, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (main.go:78)	FUNCDATA	$1, gclocals·33cdeccccebe80329f1fdbee7f5874cb(SB)
	0x001d 00029 (main.go:78)	FUNCDATA	$2, gclocals·9fb7f0986f647f17cb53dda1484e0f7a(SB)
	0x001d 00029 (main.go:79)	PCDATA	$0, $0
	0x001d 00029 (main.go:79)	PCDATA	$1, $0
	0x001d 00029 (<unknown line number>)	NOP
	0x001d 00029 (main.go:79)	PCDATA	$0, $1
	0x001d 00029 (main.go:79)	MOVQ	math/rand.globalRand(SB), AX
	0x0024 00036 ($GOROOT/src/math/rand/rand.go:329)	PCDATA	$0, $0
	0x0024 00036 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	AX, (SP)
	0x0028 00040 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	$100, 8(SP)
	0x0031 00049 ($GOROOT/src/math/rand/rand.go:329)	CALL	math/rand.(*Rand).Intn(SB)
	0x0036 00054 ($GOROOT/src/math/rand/rand.go:329)	MOVQ	16(SP), AX
	0x003b 00059 (main.go:79)	MOVQ	AX, "".x+24(SP)
	0x0040 00064 (main.go:80)	PCDATA	$0, $1
	0x0040 00064 (main.go:80)	LEAQ	"".x+24(SP), AX
	0x0045 00069 (main.go:80)	PCDATA	$0, $0
	0x0045 00069 (main.go:80)	MOVQ	AX, (SP)
	0x0049 00073 (main.go:80)	CALL	"".UnsafeParameter(SB)
	0x004e 00078 (main.go:81)	MOVB	$1, "".~r0+48(SP)
	0x0053 00083 (main.go:81)	MOVQ	32(SP), BP
	0x0058 00088 (main.go:81)	ADDQ	$40, SP
	0x005c 00092 (main.go:81)	RET
	0x005d 00093 (main.go:81)	NOP
	0x005d 00093 (main.go:78)	PCDATA	$1, $-1
	0x005d 00093 (main.go:78)	PCDATA	$0, $-1
	0x005d 00093 (main.go:78)	CALL	runtime.morestack_noctxt(SB)
	0x0062 00098 (main.go:78)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 76 4e 48  dH..%....H;a.vNH
	0x0010 83 ec 28 48 89 6c 24 20 48 8d 6c 24 20 48 8b 05  ..(H.l$ H.l$ H..
	0x0020 00 00 00 00 48 89 04 24 48 c7 44 24 08 64 00 00  ....H..$H.D$.d..
	0x0030 00 e8 00 00 00 00 48 8b 44 24 10 48 89 44 24 18  ......H.D$.H.D$.
	0x0040 48 8d 44 24 18 48 89 04 24 e8 00 00 00 00 c6 44  H.D$.H..$......D
	0x0050 24 30 01 48 8b 6c 24 20 48 83 c4 28 c3 e8 00 00  $0.H.l$ H..(....
	0x0060 00 00 eb 9c                                      ....
	rel 5+4 t=16 TLS+0
	rel 32+4 t=15 math/rand.globalRand+0
	rel 50+4 t=8 math/rand.(*Rand).Intn+0
	rel 74+4 t=8 "".UnsafeParameter+0
	rel 94+4 t=8 runtime.morestack_noctxt+0
"".main STEXT size=190 args=0x0 locals=0x68
	0x0000 00000 (main.go:84)	TEXT	"".main(SB), ABIInternal, $104-0
	0x0000 00000 (main.go:84)	MOVQ	(TLS), CX
	0x0009 00009 (main.go:84)	CMPQ	SP, 16(CX)
	0x000d 00013 (main.go:84)	JLS	180
	0x0013 00019 (main.go:84)	SUBQ	$104, SP
	0x0017 00023 (main.go:84)	MOVQ	BP, 96(SP)
	0x001c 00028 (main.go:84)	LEAQ	96(SP), BP
	0x0021 00033 (main.go:84)	FUNCDATA	$0, gclocals·69c1753bd5f81501d95132d08af04464(SB)
	0x0021 00033 (main.go:84)	FUNCDATA	$1, gclocals·568470801006e5c0dc3947ea998fe279(SB)
	0x0021 00033 (main.go:84)	FUNCDATA	$2, gclocals·bfec7e55b3f043d1941c093912808913(SB)
	0x0021 00033 (main.go:84)	FUNCDATA	$3, "".main.stkobj(SB)
	0x0021 00033 (main.go:94)	PCDATA	$0, $0
	0x0021 00033 (main.go:94)	PCDATA	$1, $0
	0x0021 00033 (main.go:94)	CALL	"".UnsafeDefinition(SB)
	0x0026 00038 (main.go:96)	CALL	"".UnsafeParameter(SB)
	0x002b 00043 (main.go:98)	CALL	"".UnsafeAssignment(SB)
	0x0030 00048 (main.go:100)	CALL	"".UnsafeCall(SB)
	0x0035 00053 (main.go:104)	CALL	"".GetBytes(SB)
	0x003a 00058 (main.go:105)	CALL	runtime.convTslice(SB)
	0x003f 00063 (main.go:105)	PCDATA	$0, $1
	0x003f 00063 (main.go:105)	MOVQ	24(SP), AX
	0x0044 00068 (main.go:105)	PCDATA	$1, $1
	0x0044 00068 (main.go:105)	XORPS	X0, X0
	0x0047 00071 (main.go:105)	MOVUPS	X0, ""..autotmp_18+80(SP)
	0x004c 00076 (main.go:105)	PCDATA	$0, $2
	0x004c 00076 (main.go:105)	LEAQ	type.[]uint8(SB), CX
	0x0053 00083 (main.go:105)	PCDATA	$0, $1
	0x0053 00083 (main.go:105)	MOVQ	CX, ""..autotmp_18+80(SP)
	0x0058 00088 (main.go:105)	PCDATA	$0, $0
	0x0058 00088 (main.go:105)	MOVQ	AX, ""..autotmp_18+88(SP)
	0x005d 00093 (<unknown line number>)	NOP
	0x005d 00093 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x005d 00093 ($GOROOT/src/fmt/print.go:213)	MOVQ	os.Stdout(SB), AX
	0x0064 00100 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $2
	0x0064 00100 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.itab.*os.File,io.Writer(SB), CX
	0x006b 00107 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x006b 00107 ($GOROOT/src/fmt/print.go:213)	MOVQ	CX, (SP)
	0x006f 00111 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x006f 00111 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 8(SP)
	0x0074 00116 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x0074 00116 ($GOROOT/src/fmt/print.go:213)	LEAQ	go.string."main: %s\n"(SB), AX
	0x007b 00123 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x007b 00123 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 16(SP)
	0x0080 00128 ($GOROOT/src/fmt/print.go:213)	MOVQ	$9, 24(SP)
	0x0089 00137 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $1
	0x0089 00137 ($GOROOT/src/fmt/print.go:213)	PCDATA	$1, $0
	0x0089 00137 ($GOROOT/src/fmt/print.go:213)	LEAQ	""..autotmp_18+80(SP), AX
	0x008e 00142 ($GOROOT/src/fmt/print.go:213)	PCDATA	$0, $0
	0x008e 00142 ($GOROOT/src/fmt/print.go:213)	MOVQ	AX, 32(SP)
	0x0093 00147 ($GOROOT/src/fmt/print.go:213)	MOVQ	$1, 40(SP)
	0x009c 00156 ($GOROOT/src/fmt/print.go:213)	MOVQ	$1, 48(SP)
	0x00a5 00165 ($GOROOT/src/fmt/print.go:213)	CALL	fmt.Fprintf(SB)
	0x00aa 00170 (<unknown line number>)	MOVQ	96(SP), BP
	0x00af 00175 (<unknown line number>)	ADDQ	$104, SP
	0x00b3 00179 (<unknown line number>)	RET
	0x00b4 00180 (<unknown line number>)	NOP
	0x00b4 00180 (main.go:84)	PCDATA	$1, $-1
	0x00b4 00180 (main.go:84)	PCDATA	$0, $-1
	0x00b4 00180 (main.go:84)	CALL	runtime.morestack_noctxt(SB)
	0x00b9 00185 (main.go:84)	JMP	0
	0x0000 64 48 8b 0c 25 00 00 00 00 48 3b 61 10 0f 86 a1  dH..%....H;a....
	0x0010 00 00 00 48 83 ec 68 48 89 6c 24 60 48 8d 6c 24  ...H..hH.l$`H.l$
	0x0020 60 e8 00 00 00 00 e8 00 00 00 00 e8 00 00 00 00  `...............
	0x0030 e8 00 00 00 00 e8 00 00 00 00 e8 00 00 00 00 48  ...............H
	0x0040 8b 44 24 18 0f 57 c0 0f 11 44 24 50 48 8d 0d 00  .D$..W...D$PH...
	0x0050 00 00 00 48 89 4c 24 50 48 89 44 24 58 48 8b 05  ...H.L$PH.D$XH..
	0x0060 00 00 00 00 48 8d 0d 00 00 00 00 48 89 0c 24 48  ....H......H..$H
	0x0070 89 44 24 08 48 8d 05 00 00 00 00 48 89 44 24 10  .D$.H......H.D$.
	0x0080 48 c7 44 24 18 09 00 00 00 48 8d 44 24 50 48 89  H.D$.....H.D$PH.
	0x0090 44 24 20 48 c7 44 24 28 01 00 00 00 48 c7 44 24  D$ H.D$(....H.D$
	0x00a0 30 01 00 00 00 e8 00 00 00 00 48 8b 6c 24 60 48  0.........H.l$`H
	0x00b0 83 c4 68 c3 e8 00 00 00 00 e9 42 ff ff ff        ..h.......B...
	rel 5+4 t=16 TLS+0
	rel 34+4 t=8 "".UnsafeDefinition+0
	rel 39+4 t=8 "".UnsafeParameter+0
	rel 44+4 t=8 "".UnsafeAssignment+0
	rel 49+4 t=8 "".UnsafeCall+0
	rel 54+4 t=8 "".GetBytes+0
	rel 59+4 t=8 runtime.convTslice+0
	rel 79+4 t=15 type.[]uint8+0
	rel 96+4 t=15 os.Stdout+0
	rel 103+4 t=15 go.itab.*os.File,io.Writer+0
	rel 119+4 t=15 go.string."main: %s\n"+0
	rel 166+4 t=8 fmt.Fprintf+0
	rel 181+4 t=8 runtime.morestack_noctxt+0
go.cuinfo.packagename. SDWARFINFO dupok size=0
	0x0000 6d 61 69 6e                                      main
go.info.strings.NewReader$abstract SDWARFINFO dupok size=30
	0x0000 04 73 74 72 69 6e 67 73 2e 4e 65 77 52 65 61 64  .strings.NewRead
	0x0010 65 72 00 01 01 11 73 00 00 00 00 00 00 00        er....s.......
	rel 25+4 t=28 go.info.string+0
go.info.bufio.NewReader$abstract SDWARFINFO dupok size=29
	0x0000 04 62 75 66 69 6f 2e 4e 65 77 52 65 61 64 65 72  .bufio.NewReader
	0x0010 00 01 01 11 72 64 00 00 00 00 00 00 00           ....rd.......
	rel 24+4 t=28 go.info.io.Reader+0
go.info.bufio.NewReaderSize$abstract SDWARFINFO dupok size=69
	0x0000 04 62 75 66 69 6f 2e 4e 65 77 52 65 61 64 65 72  .bufio.NewReader
	0x0010 53 69 7a 65 00 01 01 11 72 64 00 00 00 00 00 00  Size....rd......
	0x0020 11 73 69 7a 65 00 00 00 00 00 00 0c 62 00 30 00  .size.......b.0.
	0x0030 00 00 00 0c 6f 6b 00 30 00 00 00 00 0c 72 00 37  ....ok.0.....r.7
	0x0040 00 00 00 00 00                                   .....
	rel 28+4 t=28 go.info.io.Reader+0
	rel 39+4 t=28 go.info.int+0
	rel 47+4 t=28 go.info.*bufio.Reader+0
	rel 56+4 t=28 go.info.bool+0
	rel 64+4 t=28 go.info.*bufio.Reader+0
go.info.bufio.(*Reader).reset$abstract SDWARFINFO dupok size=52
	0x0000 04 62 75 66 69 6f 2e 28 2a 52 65 61 64 65 72 29  .bufio.(*Reader)
	0x0010 2e 72 65 73 65 74 00 01 01 11 62 00 00 00 00 00  .reset....b.....
	0x0020 00 11 62 75 66 00 00 00 00 00 00 11 72 00 00 00  ..buf.......r...
	0x0030 00 00 00 00                                      ....
	rel 29+4 t=28 go.info.*bufio.Reader+0
	rel 39+4 t=28 go.info.[]uint8+0
	rel 47+4 t=28 go.info.io.Reader+0
go.info.bufio.(*Reader).ReadString$abstract SDWARFINFO dupok size=75
	0x0000 04 62 75 66 69 6f 2e 28 2a 52 65 61 64 65 72 29  .bufio.(*Reader)
	0x0010 2e 52 65 61 64 53 74 72 69 6e 67 00 01 01 11 62  .ReadString....b
	0x0020 00 00 00 00 00 00 11 64 65 6c 69 6d 00 00 00 00  .......delim....
	0x0030 00 00 0c 62 79 74 65 73 00 dd 03 00 00 00 00 0c  ...bytes........
	0x0040 65 72 72 00 dd 03 00 00 00 00 00                 err........
	rel 34+4 t=28 go.info.*bufio.Reader+0
	rel 46+4 t=28 go.info.uint8+0
	rel 59+4 t=28 go.info.[]uint8+0
	rel 70+4 t=28 go.info.error+0
go.info."".StringToBytes$abstract SDWARFINFO dupok size=61
	0x0000 04 2e 53 74 72 69 6e 67 54 6f 42 79 74 65 73 00  ..StringToBytes.
	0x0010 01 01 11 73 00 00 00 00 00 00 0c 73 74 72 48 65  ...s.......strHe
	0x0020 61 64 65 72 00 21 00 00 00 00 0c 62 79 74 65 73  ader.!.....bytes
	0x0030 48 65 61 64 65 72 00 22 00 00 00 00 00           Header.".....
	rel 22+4 t=28 go.info.string+0
	rel 38+4 t=28 go.info.*reflect.StringHeader+0
	rel 56+4 t=28 go.info.reflect.SliceHeader+0
go.info.fmt.Printf$abstract SDWARFINFO dupok size=54
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 66 00 01 01 11 66  .fmt.Printf....f
	0x0010 6f 72 6d 61 74 00 00 00 00 00 00 11 61 00 00 00  ormat.......a...
	0x0020 00 00 00 11 6e 00 01 00 00 00 00 11 65 72 72 00  ....n.......err.
	0x0030 01 00 00 00 00 00                                ......
	rel 23+4 t=28 go.info.string+0
	rel 31+4 t=28 go.info.[]interface {}+0
	rel 39+4 t=28 go.info.int+0
	rel 49+4 t=28 go.info.error+0
go.info.math/rand.Intn$abstract SDWARFINFO dupok size=27
	0x0000 04 6d 61 74 68 2f 72 61 6e 64 2e 49 6e 74 6e 00  .math/rand.Intn.
	0x0010 01 01 11 6e 00 00 00 00 00 00 00                 ...n.......
	rel 22+4 t=28 go.info.int+0
go.info.fmt.Println$abstract SDWARFINFO dupok size=42
	0x0000 04 66 6d 74 2e 50 72 69 6e 74 6c 6e 00 01 01 11  .fmt.Println....
	0x0010 61 00 00 00 00 00 00 11 6e 00 01 00 00 00 00 11  a.......n.......
	0x0020 65 72 72 00 01 00 00 00 00 00                    err.......
	rel 19+4 t=28 go.info.[]interface {}+0
	rel 27+4 t=28 go.info.int+0
	rel 37+4 t=28 go.info.error+0
go.loc.os.(*File).close SDWARFLOC dupok size=0
go.info.os.(*File).close SDWARFINFO dupok size=55
	0x0000 03 6f 73 2e 28 2a 46 69 6c 65 29 2e 63 6c 6f 73  .os.(*File).clos
	0x0010 65 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  e...............
	0x0020 00 00 01 9c 00 00 00 00 01 0f 7e 72 30 00 01 ec  ..........~r0...
	0x0030 01 00 00 00 00 00 00                             .......
	rel 18+8 t=1 os.(*File).close+0
	rel 26+8 t=1 os.(*File).close+26
	rel 36+4 t=29 gofile..<autogenerated>+0
	rel 49+4 t=28 go.info.error+0
go.range.os.(*File).close SDWARFRANGE dupok size=0
go.isstmt.os.(*File).close SDWARFMISC dupok size=0
	0x0000 04 05 01 10 02 05 00                             .......
go.loc."".StringToBytes SDWARFLOC size=52
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 11 00 00 00 00 00 00 00 58 00 00 00 00 00 00 00  ........X.......
	0x0020 02 00 91 58 00 00 00 00 00 00 00 00 00 00 00 00  ...X............
	0x0030 00 00 00 00                                      ....
	rel 8+8 t=1 "".StringToBytes+0
go.info."".StringToBytes SDWARFINFO size=57
	0x0000 05 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 01 9c 12 00 00 00 00 00 0f 7e 72  ..............~r
	0x0020 31 00 01 20 00 00 00 00 00 0d 00 00 00 00 00 0e  1.. ............
	0x0030 00 00 00 00 00 00 00 00 00                       .........
	rel 1+4 t=28 go.info."".StringToBytes$abstract+0
	rel 5+8 t=1 "".StringToBytes+0
	rel 13+8 t=1 "".StringToBytes+88
	rel 24+4 t=28 go.info."".StringToBytes$abstract+18
	rel 36+4 t=28 go.info.[]uint8+0
	rel 42+4 t=28 go.info."".StringToBytes$abstract+26
	rel 48+4 t=28 go.info."".StringToBytes$abstract+42
	rel 52+4 t=28 go.loc."".StringToBytes+0
go.range."".StringToBytes SDWARFRANGE size=0
go.isstmt."".StringToBytes SDWARFMISC size=0
	0x0000 08 0e 03 03 01 0d 02 05 01 04 02 05 01 05 02 05  ................
	0x0010 01 05 02 04 01 19 00                             .......
go.string."hello!123" SRODATA dupok size=9
	0x0000 68 65 6c 6c 6f 21 31 32 33                       hello!123
go.string."GetBytes: %s\n" SRODATA dupok size=13
	0x0000 47 65 74 42 79 74 65 73 3a 20 25 73 0a           GetBytes: %s.
go.loc."".GetBytes SDWARFLOC size=750
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 30 02 00 00 00 00 00 00 4b 02 00 00 00 00 00 00  0.......K.......
	0x0020 01 00 51 4b 02 00 00 00 00 00 00 fc 02 00 00 00  ..QK............
	0x0030 00 00 00 03 00 91 90 7e 00 00 00 00 00 00 00 00  .......~........
	0x0040 00 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff  ................
	0x0050 00 00 00 00 00 00 00 00 d4 01 00 00 00 00 00 00  ................
	0x0060 d9 01 00 00 00 00 00 00 05 00 93 08 50 93 08 d9  ............P...
	0x0070 01 00 00 00 00 00 00 02 02 00 00 00 00 00 00 06  ................
	0x0080 00 52 93 08 50 93 08 02 02 00 00 00 00 00 00 21  .R..P..........!
	0x0090 02 00 00 00 00 00 00 05 00 52 93 08 93 08 00 00  .........R......
	0x00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ff ff  ................
	0x00b0 ff ff ff ff ff ff 00 00 00 00 00 00 00 00 47 00  ..............G.
	0x00c0 00 00 00 00 00 00 93 00 00 00 00 00 00 00 05 00  ................
	0x00d0 93 08 55 93 08 93 00 00 00 00 00 00 00 fc 02 00  ..U.............
	0x00e0 00 00 00 00 00 07 00 93 08 91 98 7e 93 08 fc 02  ...........~....
	0x00f0 00 00 00 00 00 00 17 03 00 00 00 00 00 00 05 00  ................
	0x0100 93 08 55 93 08 00 00 00 00 00 00 00 00 00 00 00  ..U.............
	0x0110 00 00 00 00 00 ff ff ff ff ff ff ff ff 00 00 00  ................
	0x0120 00 00 00 00 00 47 00 00 00 00 00 00 00 93 00 00  .....G..........
	0x0130 00 00 00 00 00 05 00 93 08 55 93 08 93 00 00 00  .........U......
	0x0140 00 00 00 00 fc 02 00 00 00 00 00 00 07 00 93 08  ................
	0x0150 91 98 7e 93 08 fc 02 00 00 00 00 00 00 17 03 00  ..~.............
	0x0160 00 00 00 00 00 05 00 93 08 55 93 08 00 00 00 00  .........U......
	0x0170 00 00 00 00 00 00 00 00 00 00 00 00 ff ff ff ff  ................
	0x0180 ff ff ff ff 00 00 00 00 00 00 00 00 d4 00 00 00  ................
	0x0190 00 00 00 00 29 01 00 00 00 00 00 00 01 00 50 00  ....).........P.
	0x01a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 ff  ................
	0x01b0 ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00 47  ...............G
	0x01c0 00 00 00 00 00 00 00 93 00 00 00 00 00 00 00 05  ................
	0x01d0 00 93 08 55 93 08 93 00 00 00 00 00 00 00 fc 02  ...U............
	0x01e0 00 00 00 00 00 00 07 00 93 08 91 98 7e 93 08 fc  ............~...
	0x01f0 02 00 00 00 00 00 00 17 03 00 00 00 00 00 00 05  ................
	0x0200 00 93 08 55 93 08 00 00 00 00 00 00 00 00 00 00  ...U............
	0x0210 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00 00  ................
	0x0220 00 00 00 00 00 00 a8 01 00 00 00 00 00 00 ad 01  ................
	0x0230 00 00 00 00 00 00 07 00 93 08 93 08 50 93 08 ad  ............P...
	0x0240 01 00 00 00 00 00 00 b2 01 00 00 00 00 00 00 08  ................
	0x0250 00 93 08 52 93 08 50 93 08 b2 01 00 00 00 00 00  ...R..P.........
	0x0260 00 cf 01 00 00 00 00 00 00 09 00 51 93 08 52 93  ...........Q..R.
	0x0270 08 50 93 08 00 00 00 00 00 00 00 00 00 00 00 00  .P..............
	0x0280 00 00 00 00 ff ff ff ff ff ff ff ff 00 00 00 00  ................
	0x0290 00 00 00 00 e1 01 00 00 00 00 00 00 fc 02 00 00  ................
	0x02a0 00 00 00 00 03 00 91 a0 7e 00 00 00 00 00 00 00  ........~.......
	0x02b0 00 00 00 00 00 00 00 00 00 ff ff ff ff ff ff ff  ................
	0x02c0 ff 00 00 00 00 00 00 00 00 ec 01 00 00 00 00 00  ................
	0x02d0 00 fc 02 00 00 00 00 00 00 03 00 91 d8 7d 00 00  .............}..
	0x02e0 00 00 00 00 00 00 00 00 00 00 00 00 00 00        ..............
	rel 8+8 t=1 "".GetBytes+0
	rel 80+8 t=1 "".GetBytes+0
	rel 182+8 t=1 "".GetBytes+0
	rel 285+8 t=1 "".GetBytes+0
	rel 388+8 t=1 "".GetBytes+0
	rel 439+8 t=1 "".GetBytes+0
	rel 542+8 t=1 "".GetBytes+0
	rel 652+8 t=1 "".GetBytes+0
	rel 705+8 t=1 "".GetBytes+0
go.info."".GetBytes SDWARFINFO size=321
	0x0000 03 22 22 2e 47 65 74 42 79 74 65 73 00 00 00 00  ."".GetBytes....
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 01 9c 00  ................
	0x0020 00 00 00 01 0b 6f 75 74 00 2d 00 00 00 00 00 00  .....out.-......
	0x0030 00 00 0b 73 00 2c 00 00 00 00 00 00 00 00 0f 7e  ...s.,.........~
	0x0040 72 30 00 01 2a 00 00 00 00 00 07 00 00 00 00 00  r0..*...........
	0x0050 00 00 00 00 00 00 00 2b 00 06 00 00 00 00 00 00  .......+........
	0x0060 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0070 00 00 2b 13 00 00 00 00 00 00 00 00 06 00 00 00  ..+.............
	0x0080 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0090 00 00 00 00 00 3e 13 00 00 00 00 00 00 00 00 06  .....>..........
	0x00a0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x00b0 00 00 00 00 00 00 00 00 38 13 00 00 00 00 00 00  ........8.......
	0x00c0 00 00 13 00 00 00 00 00 00 00 00 00 00 00 06 00  ................
	0x00d0 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x00e0 00 00 00 00 00 00 00 2c 0e 00 00 00 00 00 00 00  .......,........
	0x00f0 00 00 06 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0100 00 00 00 00 00 00 00 00 00 00 00 2d 13 00 00 00  ...........-....
	0x0110 00 00 00 00 00 0e 00 00 00 00 00 00 00 00 00 06  ................
	0x0120 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0130 00 00 00 00 00 00 00 00 2e 12 00 00 00 00 00 00  ................
	0x0140 00                                               .
	rel 13+8 t=1 "".GetBytes+0
	rel 21+8 t=1 "".GetBytes+791
	rel 31+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 42+4 t=28 go.info.[]uint8+0
	rel 46+4 t=28 go.loc."".GetBytes+0
	rel 54+4 t=28 go.info.string+0
	rel 58+4 t=28 go.loc."".GetBytes+72
	rel 69+4 t=28 go.info.[]uint8+0
	rel 75+4 t=28 go.info.strings.NewReader$abstract+0
	rel 79+4 t=28 go.range."".GetBytes+0
	rel 83+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 90+4 t=28 go.info.bufio.NewReader$abstract+0
	rel 94+8 t=1 "".GetBytes+126
	rel 102+8 t=1 "".GetBytes+127
	rel 110+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 116+4 t=28 go.info.bufio.NewReader$abstract+19
	rel 120+4 t=28 go.loc."".GetBytes+174
	rel 125+4 t=28 go.info.bufio.NewReaderSize$abstract+0
	rel 129+8 t=1 "".GetBytes+127
	rel 137+8 t=1 "".GetBytes+212
	rel 145+4 t=29 gofile..$GOROOT/src/bufio/bufio.go+0
	rel 151+4 t=28 go.info.bufio.NewReaderSize$abstract+23
	rel 155+4 t=28 go.loc."".GetBytes+277
	rel 160+4 t=28 go.info.bufio.(*Reader).reset$abstract+0
	rel 164+8 t=1 "".GetBytes+212
	rel 172+8 t=1 "".GetBytes+396
	rel 180+4 t=29 gofile..$GOROOT/src/bufio/bufio.go+0
	rel 186+4 t=28 go.info.bufio.(*Reader).reset$abstract+33
	rel 190+4 t=28 go.loc."".GetBytes+380
	rel 195+4 t=28 go.info.bufio.(*Reader).reset$abstract+43
	rel 199+4 t=28 go.loc."".GetBytes+431
	rel 207+4 t=28 go.info.bufio.(*Reader).ReadString$abstract+0
	rel 211+8 t=1 "".GetBytes+397
	rel 219+8 t=1 "".GetBytes+473
	rel 227+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 233+4 t=28 go.info.bufio.(*Reader).ReadString$abstract+50
	rel 237+4 t=28 go.loc."".GetBytes+534
	rel 243+4 t=28 go.info."".StringToBytes$abstract+0
	rel 247+8 t=1 "".GetBytes+489
	rel 255+8 t=1 "".GetBytes+568
	rel 263+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 269+4 t=28 go.info."".StringToBytes$abstract+18
	rel 273+4 t=28 go.loc."".GetBytes+644
	rel 278+4 t=28 go.info."".StringToBytes$abstract+42
	rel 282+4 t=28 go.loc."".GetBytes+697
	rel 288+4 t=28 go.info.fmt.Printf$abstract+0
	rel 292+8 t=1 "".GetBytes+626
	rel 300+8 t=1 "".GetBytes+706
	rel 308+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 314+4 t=28 go.info.fmt.Printf$abstract+14
go.range."".GetBytes SDWARFRANGE size=64
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 39 00 00 00 00 00 00 00 7e 00 00 00 00 00 00 00  9.......~.......
	0x0020 fc 02 00 00 00 00 00 00 0d 03 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 8+8 t=1 "".GetBytes+0
go.isstmt."".GetBytes SDWARFMISC size=0
	0x0000 04 1b 04 17 03 10 01 3c 02 0d 01 22 02 07 01 16  .......<..."....
	0x0010 02 05 01 05 02 0c 01 ac 01 02 09 01 09 02 05 01  ................
	0x0020 0f 02 05 01 13 02 05 01 0a 02 08 01 08 02 03 01  ................
	0x0030 0e 02 08 01 05 02 08 01 0a 02 08 01 0a 02 05 01  ................
	0x0040 08 02 04 01 0a 02 05 01 27 02 07 01 44 02 0d 01  ........'...D...
	0x0050 43 02 0a 00                                      C...
runtime.gcbits.01 SRODATA dupok size=1
	0x0000 01                                               .
type..namedata.*interface {}- SRODATA dupok size=16
	0x0000 00 00 0d 2a 69 6e 74 65 72 66 61 63 65 20 7b 7d  ...*interface {}
type.*interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 4f 0f 96 9d 00 08 08 36 00 00 00 00 00 00 00 00  O......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 48+8 t=1 type.interface {}+0
runtime.gcbits.02 SRODATA dupok size=1
	0x0000 02                                               .
type.interface {} SRODATA dupok size=80
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 e7 57 a0 18 02 08 08 14 00 00 00 00 00 00 00 00  .W..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*interface {}-+0
	rel 44+4 t=6 type.*interface {}+0
	rel 56+8 t=1 type.interface {}+80
type..namedata.*[]interface {}- SRODATA dupok size=18
	0x0000 00 00 0f 2a 5b 5d 69 6e 74 65 72 66 61 63 65 20  ...*[]interface 
	0x0010 7b 7d                                            {}
type.*[]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f3 04 9a e7 00 08 08 36 00 00 00 00 00 00 00 00  .......6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 48+8 t=1 type.[]interface {}+0
type.[]interface {} SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 70 93 ea 2f 02 08 08 17 00 00 00 00 00 00 00 00  p../............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]interface {}-+0
	rel 44+4 t=6 type.*[]interface {}+0
	rel 48+8 t=1 type.interface {}+0
type..namedata.*[1]interface {}- SRODATA dupok size=19
	0x0000 00 00 10 2a 5b 31 5d 69 6e 74 65 72 66 61 63 65  ...*[1]interface
	0x0010 20 7b 7d                                          {}
type.*[1]interface {} SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 bf 03 a8 35 00 08 08 36 00 00 00 00 00 00 00 00  ...5...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 48+8 t=1 type.[1]interface {}+0
type.[1]interface {} SRODATA dupok size=72
	0x0000 10 00 00 00 00 00 00 00 10 00 00 00 00 00 00 00  ................
	0x0010 50 91 5b fa 02 08 08 11 00 00 00 00 00 00 00 00  P.[.............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 01 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+144
	rel 32+8 t=1 runtime.gcbits.02+0
	rel 40+4 t=5 type..namedata.*[1]interface {}-+0
	rel 44+4 t=6 type.*[1]interface {}+0
	rel 48+8 t=1 type.interface {}+0
	rel 56+8 t=1 type.[]interface {}+0
go.string."bingo!" SRODATA dupok size=6
	0x0000 62 69 6e 67 6f 21                                bingo!
go.loc."".UnsafeDefinition SDWARFLOC size=142
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 36 00 00 00 00 00 00 00 54 00 00 00 00 00 00 00  6.......T.......
	0x0020 01 00 50 54 00 00 00 00 00 00 00 e4 00 00 00 00  ..PT............
	0x0030 00 00 00 02 00 91 58 00 00 00 00 00 00 00 00 00  ......X.........
	0x0040 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00  ................
	0x0050 00 00 00 00 00 00 00 36 00 00 00 00 00 00 00 54  .......6.......T
	0x0060 00 00 00 00 00 00 00 01 00 50 54 00 00 00 00 00  .........PT.....
	0x0070 00 00 e4 00 00 00 00 00 00 00 02 00 91 58 00 00  .............X..
	0x0080 00 00 00 00 00 00 00 00 00 00 00 00 00 00        ..............
	rel 8+8 t=1 "".UnsafeDefinition+0
	rel 79+8 t=1 "".UnsafeDefinition+0
go.info."".UnsafeDefinition SDWARFINFO size=136
	0x0000 03 22 22 2e 55 6e 73 61 66 65 44 65 66 69 6e 69  ."".UnsafeDefini
	0x0010 74 69 6f 6e 00 00 00 00 00 00 00 00 00 00 00 00  tion............
	0x0020 00 00 00 00 00 01 9c 00 00 00 00 01 0b 26 79 00  .............&y.
	0x0030 35 00 00 00 00 00 00 00 00 0b 78 00 34 00 00 00  5.........x.4...
	0x0040 00 00 00 00 00 0f 7e 72 30 00 01 33 00 00 00 00  ......~r0..3....
	0x0050 00 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 00 00 00 00 35 00 06 00 00 00  ..........5.....
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0080 00 00 00 00 00 38 00 00                          .....8..
	rel 21+8 t=1 "".UnsafeDefinition+0
	rel 29+8 t=1 "".UnsafeDefinition+228
	rel 39+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 49+4 t=28 go.info.*int+0
	rel 53+4 t=28 go.loc."".UnsafeDefinition+0
	rel 61+4 t=28 go.info.unsafe.Pointer+0
	rel 65+4 t=28 go.loc."".UnsafeDefinition+71
	rel 76+4 t=28 go.info.unsafe.Pointer+0
	rel 82+4 t=28 go.info.math/rand.Intn$abstract+0
	rel 86+8 t=1 "".UnsafeDefinition+59
	rel 94+8 t=1 "".UnsafeDefinition+89
	rel 102+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 109+4 t=28 go.info.fmt.Println$abstract+0
	rel 113+8 t=1 "".UnsafeDefinition+160
	rel 121+8 t=1 "".UnsafeDefinition+216
	rel 129+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
go.range."".UnsafeDefinition SDWARFRANGE size=0
go.isstmt."".UnsafeDefinition SDWARFMISC size=0
	0x0000 04 13 04 0e 03 07 01 04 02 05 01 0a 02 07 01 0d  ................
	0x0010 02 05 01 05 02 05 01 03 02 05 01 06 02 05 01 0f  ................
	0x0020 02 03 01 1d 02 07 01 2c 02 05 01 02 02 0a 00     .......,.......
go.loc."".UnsafeParameter SDWARFLOC size=122
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 49 00 00 00 00 00 00 00  ........I.......
	0x0020 01 00 50 49 00 00 00 00 00 00 00 cf 00 00 00 00  ..PI............
	0x0030 00 00 00 02 00 91 58 00 00 00 00 00 00 00 00 00  ......X.........
	0x0040 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00  ................
	0x0050 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 cf  ................
	0x0060 00 00 00 00 00 00 00 01 00 9c 00 00 00 00 00 00  ................
	0x0070 00 00 00 00 00 00 00 00 00 00                    ..........
	rel 8+8 t=1 "".UnsafeParameter+0
	rel 79+8 t=1 "".UnsafeParameter+0
go.info."".UnsafeParameter SDWARFINFO size=135
	0x0000 03 22 22 2e 55 6e 73 61 66 65 50 61 72 61 6d 65  ."".UnsafeParame
	0x0010 74 65 72 00 00 00 00 00 00 00 00 00 00 00 00 00  ter.............
	0x0020 00 00 00 00 01 9c 00 00 00 00 01 0b 79 00 3e 00  ............y.>.
	0x0030 00 00 00 00 00 00 00 10 78 00 00 3d 00 00 00 00  ........x..=....
	0x0040 00 00 00 00 0f 7e 72 31 00 01 3d 00 00 00 00 00  .....~r1..=.....
	0x0050 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 00 00 00 3e 00 06 00 00 00 00  .........>......
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0080 00 00 00 00 40 00 00                             ....@..
	rel 20+8 t=1 "".UnsafeParameter+0
	rel 28+8 t=1 "".UnsafeParameter+207
	rel 38+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 47+4 t=28 go.info.int+0
	rel 51+4 t=28 go.loc."".UnsafeParameter+0
	rel 60+4 t=28 go.info.unsafe.Pointer+0
	rel 64+4 t=28 go.loc."".UnsafeParameter+71
	rel 75+4 t=28 go.info.int+0
	rel 81+4 t=28 go.info.math/rand.Intn$abstract+0
	rel 85+8 t=1 "".UnsafeParameter+40
	rel 93+8 t=1 "".UnsafeParameter+68
	rel 101+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 108+4 t=28 go.info.fmt.Println$abstract+0
	rel 112+8 t=1 "".UnsafeParameter+139
	rel 120+8 t=1 "".UnsafeParameter+195
	rel 128+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
go.range."".UnsafeParameter SDWARFRANGE size=0
go.isstmt."".UnsafeParameter SDWARFMISC size=0
	0x0000 04 13 04 0e 03 07 01 0d 02 05 01 0a 02 05 01 06  ................
	0x0010 02 05 01 17 02 03 01 1d 02 07 01 2c 02 05 01 02  ...........,....
	0x0020 02 0a 00                                         ...
go.loc."".UnsafeAssignment SDWARFLOC size=142
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 36 00 00 00 00 00 00 00 54 00 00 00 00 00 00 00  6.......T.......
	0x0020 01 00 50 54 00 00 00 00 00 00 00 e4 00 00 00 00  ..PT............
	0x0030 00 00 00 02 00 91 58 00 00 00 00 00 00 00 00 00  ......X.........
	0x0040 00 00 00 00 00 00 00 ff ff ff ff ff ff ff ff 00  ................
	0x0050 00 00 00 00 00 00 00 36 00 00 00 00 00 00 00 54  .......6.......T
	0x0060 00 00 00 00 00 00 00 01 00 50 54 00 00 00 00 00  .........PT.....
	0x0070 00 00 e4 00 00 00 00 00 00 00 02 00 91 58 00 00  .............X..
	0x0080 00 00 00 00 00 00 00 00 00 00 00 00 00 00        ..............
	rel 8+8 t=1 "".UnsafeAssignment+0
	rel 79+8 t=1 "".UnsafeAssignment+0
go.info."".UnsafeAssignment SDWARFINFO size=136
	0x0000 03 22 22 2e 55 6e 73 61 66 65 41 73 73 69 67 6e  ."".UnsafeAssign
	0x0010 6d 65 6e 74 00 00 00 00 00 00 00 00 00 00 00 00  ment............
	0x0020 00 00 00 00 00 01 9c 00 00 00 00 01 0b 26 79 00  .............&y.
	0x0030 46 00 00 00 00 00 00 00 00 0b 78 00 47 00 00 00  F.........x.G...
	0x0040 00 00 00 00 00 0f 7e 72 30 00 01 45 00 00 00 00  ......~r0..E....
	0x0050 00 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0060 00 00 00 00 00 00 00 00 00 00 46 00 06 00 00 00  ..........F.....
	0x0070 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0080 00 00 00 00 00 49 00 00                          .....I..
	rel 21+8 t=1 "".UnsafeAssignment+0
	rel 29+8 t=1 "".UnsafeAssignment+228
	rel 39+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 49+4 t=28 go.info.*int+0
	rel 53+4 t=28 go.loc."".UnsafeAssignment+0
	rel 61+4 t=28 go.info.unsafe.Pointer+0
	rel 65+4 t=28 go.loc."".UnsafeAssignment+71
	rel 76+4 t=28 go.info.unsafe.Pointer+0
	rel 82+4 t=28 go.info.math/rand.Intn$abstract+0
	rel 86+8 t=1 "".UnsafeAssignment+59
	rel 94+8 t=1 "".UnsafeAssignment+89
	rel 102+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 109+4 t=28 go.info.fmt.Println$abstract+0
	rel 113+8 t=1 "".UnsafeAssignment+160
	rel 121+8 t=1 "".UnsafeAssignment+216
	rel 129+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
go.range."".UnsafeAssignment SDWARFRANGE size=0
go.isstmt."".UnsafeAssignment SDWARFMISC size=0
	0x0000 04 13 04 0e 03 07 01 04 02 05 01 0a 02 07 01 0d  ................
	0x0010 02 05 01 05 02 05 01 03 02 05 01 06 02 05 01 0f  ................
	0x0020 02 03 01 1d 02 07 01 2c 02 05 01 02 02 0a 00     .......,.......
go.loc."".UnsafeCall SDWARFLOC size=52
	0x0000 ff ff ff ff ff ff ff ff 00 00 00 00 00 00 00 00  ................
	0x0010 40 00 00 00 00 00 00 00 64 00 00 00 00 00 00 00  @.......d.......
	0x0020 02 00 91 68 00 00 00 00 00 00 00 00 00 00 00 00  ...h............
	0x0030 00 00 00 00                                      ....
	rel 8+8 t=1 "".UnsafeCall+0
go.info."".UnsafeCall SDWARFINFO size=90
	0x0000 03 22 22 2e 55 6e 73 61 66 65 43 61 6c 6c 00 00  ."".UnsafeCall..
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 01  ................
	0x0020 9c 00 00 00 00 01 0b 78 00 4f 00 00 00 00 00 00  .......x.O......
	0x0030 00 00 0f 7e 72 30 00 01 4e 00 00 00 00 00 06 00  ...~r0..N.......
	0x0040 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0050 00 00 00 00 00 00 00 4f 00 00                    .......O..
	rel 15+8 t=1 "".UnsafeCall+0
	rel 23+8 t=1 "".UnsafeCall+100
	rel 33+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 42+4 t=28 go.info.int+0
	rel 46+4 t=28 go.loc."".UnsafeCall+0
	rel 57+4 t=28 go.info.bool+0
	rel 63+4 t=28 go.info.math/rand.Intn$abstract+0
	rel 67+8 t=1 "".UnsafeCall+36
	rel 75+8 t=1 "".UnsafeCall+59
	rel 83+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
go.range."".UnsafeCall SDWARFRANGE size=0
go.isstmt."".UnsafeCall SDWARFMISC size=0
	0x0000 04 0f 04 0e 03 07 01 0d 02 05 01 0a 02 05 01 04  ................
	0x0010 02 0a 01 0a 02 07 00                             .......
go.string."main: %s\n" SRODATA dupok size=9
	0x0000 6d 61 69 6e 3a 20 25 73 0a                       main: %s.
go.loc."".main SDWARFLOC size=0
go.info."".main SDWARFINFO size=66
	0x0000 03 22 22 2e 6d 61 69 6e 00 00 00 00 00 00 00 00  ."".main........
	0x0010 00 00 00 00 00 00 00 00 00 01 9c 00 00 00 00 01  ................
	0x0020 06 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 69 12 00 00 00 00 00  .........i......
	0x0040 00 00                                            ..
	rel 9+8 t=1 "".main+0
	rel 17+8 t=1 "".main+190
	rel 27+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 33+4 t=28 go.info.fmt.Printf$abstract+0
	rel 37+8 t=1 "".main+93
	rel 45+8 t=1 "".main+170
	rel 53+4 t=29 gofile../mnt/d/idbs/go-hunter/little-gopher/main.go+0
	rel 59+4 t=28 go.info.fmt.Printf$abstract+14
go.range."".main SDWARFRANGE size=0
go.isstmt."".main SDWARFMISC size=0
	0x0000 04 13 04 0e 03 1e 01 1e 02 07 01 41 02 05 01 0a  ...........A....
	0x0010 02 0a 00                                         ...
""..inittask SNOPTRDATA size=64
	0x0000 00 00 00 00 00 00 00 00 05 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 24+8 t=1 fmt..inittask+0
	rel 32+8 t=1 strings..inittask+0
	rel 40+8 t=1 bufio..inittask+0
	rel 48+8 t=1 reflect..inittask+0
	rel 56+8 t=1 math/rand..inittask+0
""..stmp_0 SRODATA size=16
	0x0000 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 go.string."bingo!"+0
""..stmp_1 SRODATA size=16
	0x0000 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 go.string."bingo!"+0
""..stmp_2 SRODATA size=16
	0x0000 00 00 00 00 00 00 00 00 06 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 go.string."bingo!"+0
type..namedata.*[]uint8- SRODATA dupok size=11
	0x0000 00 00 08 2a 5b 5d 75 69 6e 74 38                 ...*[]uint8
type.*[]uint8 SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 a5 8e d0 69 00 08 08 36 00 00 00 00 00 00 00 00  ...i...6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]uint8-+0
	rel 48+8 t=1 type.[]uint8+0
type.[]uint8 SRODATA dupok size=56
	0x0000 18 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 df 7e 2e 38 02 08 08 17 00 00 00 00 00 00 00 00  .~.8............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+0
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[]uint8-+0
	rel 44+4 t=6 type.*[]uint8+0
	rel 48+8 t=1 type.uint8+0
type..hashfunc32 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00  ........ .......
	rel 0+8 t=1 runtime.memhash_varlen+0
type..eqfunc32 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 20 00 00 00 00 00 00 00  ........ .......
	rel 0+8 t=1 runtime.memequal_varlen+0
type..alg32 SRODATA dupok size=16
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 type..hashfunc32+0
	rel 8+8 t=1 type..eqfunc32+0
type..namedata.*[32]uint8- SRODATA dupok size=13
	0x0000 00 00 0a 2a 5b 33 32 5d 75 69 6e 74 38           ...*[32]uint8
type.*[32]uint8 SRODATA dupok size=56
	0x0000 08 00 00 00 00 00 00 00 08 00 00 00 00 00 00 00  ................
	0x0010 f4 c7 79 15 00 08 08 36 00 00 00 00 00 00 00 00  ..y....6........
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 24+8 t=1 runtime.algarray+80
	rel 32+8 t=1 runtime.gcbits.01+0
	rel 40+4 t=5 type..namedata.*[32]uint8-+0
	rel 48+8 t=1 type.[32]uint8+0
runtime.gcbits. SRODATA dupok size=0
type.[32]uint8 SRODATA dupok size=72
	0x0000 20 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00   ...............
	0x0010 9c 59 ff a8 02 01 01 11 00 00 00 00 00 00 00 00  .Y..............
	0x0020 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0030 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0040 20 00 00 00 00 00 00 00                           .......
	rel 24+8 t=1 type..alg32+0
	rel 32+8 t=1 runtime.gcbits.+0
	rel 40+4 t=5 type..namedata.*[32]uint8-+0
	rel 44+4 t=6 type.*[32]uint8+0
	rel 48+8 t=1 type.uint8+0
	rel 56+8 t=1 type.[]uint8+0
go.itab.*strings.Reader,io.Reader SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 7d 18 28 41 00 00 00 00 00 00 00 00 00 00 00 00  }.(A............
	rel 0+8 t=1 type.io.Reader+0
	rel 8+8 t=1 type.*strings.Reader+0
	rel 24+8 t=1 strings.(*Reader).Read+0
go.itablink.*strings.Reader,io.Reader SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*strings.Reader,io.Reader+0
go.itab.*bufio.Reader,io.Reader SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 87 9b dc af 00 00 00 00 00 00 00 00 00 00 00 00  ................
	rel 0+8 t=1 type.io.Reader+0
	rel 8+8 t=1 type.*bufio.Reader+0
	rel 24+8 t=1 bufio.(*Reader).Read+0
go.itablink.*bufio.Reader,io.Reader SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*bufio.Reader,io.Reader+0
go.itab.*os.File,io.Writer SRODATA dupok size=32
	0x0000 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 44 b5 f3 33 00 00 00 00 00 00 00 00 00 00 00 00  D..3............
	rel 0+8 t=1 type.io.Writer+0
	rel 8+8 t=1 type.*os.File+0
	rel 24+8 t=1 os.(*File).Write+0
go.itablink.*os.File,io.Writer SRODATA dupok size=8
	0x0000 00 00 00 00 00 00 00 00                          ........
	rel 0+8 t=1 go.itab.*os.File,io.Writer+0
type..importpath.bufio. SRODATA dupok size=8
	0x0000 00 00 05 62 75 66 69 6f                          ...bufio
type..importpath.fmt. SRODATA dupok size=6
	0x0000 00 00 03 66 6d 74                                ...fmt
type..importpath.math/rand. SRODATA dupok size=12
	0x0000 00 00 09 6d 61 74 68 2f 72 61 6e 64              ...math/rand
type..importpath.reflect. SRODATA dupok size=10
	0x0000 00 00 07 72 65 66 6c 65 63 74                    ...reflect
type..importpath.strings. SRODATA dupok size=10
	0x0000 00 00 07 73 74 72 69 6e 67 73                    ...strings
type..importpath.unsafe. SRODATA dupok size=9
	0x0000 00 00 06 75 6e 73 61 66 65                       ...unsafe
gclocals·e6397a44f8e1b6e77d0f200b4fba5269 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 01 00                    ..........
gclocals·69c1753bd5f81501d95132d08af04464 SRODATA dupok size=8
	0x0000 02 00 00 00 00 00 00 00                          ........
gclocals·9fb7f0986f647f17cb53dda1484e0f7a SRODATA dupok size=10
	0x0000 02 00 00 00 01 00 00 00 00 01                    ..........
gclocals·9fad110d66c97cf0b58d28cccea80b12 SRODATA dupok size=11
	0x0000 03 00 00 00 03 00 00 00 01 00 04                 ...........
gclocals·7d2d5fca80364273fb07d5820a76fef4 SRODATA dupok size=8
	0x0000 03 00 00 00 00 00 00 00                          ........
gclocals·ebb0e8ce1793da18f0378b883cb3e122 SRODATA dupok size=10
	0x0000 02 00 00 00 03 00 00 00 00 04                    ..........
"".StringToBytes.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.string+0
gclocals·4dea565f520afaadcafa547fa021b9b7 SRODATA dupok size=18
	0x0000 0a 00 00 00 01 00 00 00 00 00 00 00 00 00 00 00  ................
	0x0010 00 01                                            ..
gclocals·0ab7ac59bd0f2fcbe06e59c253658797 SRODATA dupok size=48
	0x0000 0a 00 00 00 1c 00 00 00 00 00 00 00 02 00 00 00  ................
	0x0010 02 00 22 02 42 44 22 02 40 44 22 02 00 00 22 02  ..".BD".@D"...".
	0x0020 04 00 00 00 01 00 00 00 21 00 00 00 00 00 00 00  ........!.......
gclocals·7a658a2e7258b83e869501a01ac51f46 SRODATA dupok size=17
	0x0000 09 00 00 00 07 00 00 00 00 01 40 02 41 60 04 0c  ..........@.A`..
	0x0010 03                                               .
"".GetBytes.stkobj SRODATA dupok size=56
	0x0000 03 00 00 00 00 00 00 00 30 ff ff ff ff ff ff ff  ........0.......
	0x0010 00 00 00 00 00 00 00 00 40 ff ff ff ff ff ff ff  ........@.......
	0x0020 00 00 00 00 00 00 00 00 a8 ff ff ff ff ff ff ff  ................
	0x0030 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.string+0
	rel 32+8 t=1 type.[1]interface {}+0
	rel 48+8 t=1 type.bufio.Reader+0
gclocals·a5055cd68876ca89b660e46f7e21fd17 SRODATA dupok size=12
	0x0000 04 00 00 00 01 00 00 00 00 00 01 00              ............
gclocals·4ef8357644ec89b6336b31bfc1bf9954 SRODATA dupok size=12
	0x0000 04 00 00 00 03 00 00 00 00 01 00 05              ............
gclocals·ba192201ac73f95fb90b551d9176d705 SRODATA dupok size=12
	0x0000 04 00 00 00 02 00 00 00 00 01 02 03              ............
"".UnsafeDefinition.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·1ff8b8d8bc8134ef1359e077847f1272 SRODATA dupok size=11
	0x0000 03 00 00 00 01 00 00 00 01 00 01                 ...........
gclocals·ffd148479e14c29ee3c68361945c5d25 SRODATA dupok size=11
	0x0000 03 00 00 00 02 00 00 00 00 00 02                 ...........
"".UnsafeParameter.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
"".UnsafeAssignment.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
gclocals·33cdeccccebe80329f1fdbee7f5874cb SRODATA dupok size=8
	0x0000 01 00 00 00 00 00 00 00                          ........
gclocals·568470801006e5c0dc3947ea998fe279 SRODATA dupok size=10
	0x0000 02 00 00 00 02 00 00 00 00 02                    ..........
gclocals·bfec7e55b3f043d1941c093912808913 SRODATA dupok size=11
	0x0000 03 00 00 00 02 00 00 00 00 01 03                 ...........
"".main.stkobj SRODATA dupok size=24
	0x0000 01 00 00 00 00 00 00 00 f0 ff ff ff ff ff ff ff  ................
	0x0010 00 00 00 00 00 00 00 00                          ........
	rel 16+8 t=1 type.[1]interface {}+0
